Repository woowacourse-teams/2024-touroot, pull requests merged in 2024-07, with the labels that each got.

#4 [Feature] - 프로젝트 환경 세팅
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.prettierrc.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/styles/globalStyle.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: FE, chore

#3 [Feature] - 프로젝트 세팅
  backend/.gitignore
  backend/HELP.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/woowacourse/touroot/TourootApplication.java
  backend/src/main/resources/application.yml
  backend/src/test/java/woowacourse/touroot/TourootApplicationTests.java
Labels: BE

#7 [Feature] - API 자동 문서화 사전 작업
  backend/build.gradle
  backend/src/main/java/woowacourse/touroot/global/config/SwaggerConfig.java
Labels: BE

#10 [Feature] - DockerFile 작성
  backend/Dockerfile
Labels: BE

#12 [Feature] CI/CD Pipeline 구축
  .github/workflows/be-dev-ci.yml
Labels: BE

#14 [Feature] - Docker Push / Docker Build CI workflow 추가
  .github/workflows/be-dev-ci.yml
Labels: BE

#16 [Fix] - CI workflow docker image platform 변경
  .github/workflows/be-dev-ci.yml
Labels: BE

#19 [Feature] - Ping api
  backend/src/main/java/woowacourse/touroot/PingController.java
Labels: BE

#21 feat: 여행기 관련 Entity 생성
  backend/src/main/java/woowacourse/touroot/place/domain/Place.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/woowacourse/touroot/travelogueday/domain/TravelogueDay.java
  backend/src/main/java/woowacourse/touroot/traveloguephoto/domain/TraveloguePhoto.java
  backend/src/main/java/woowacourse/touroot/travelogueplace/domain/TraveloguePlace.java
Labels: BE

#24 [Fix] - Database 예약어였던 Entity 필드명 수정
  backend/src/main/java/woowacourse/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/woowacourse/touroot/travelogueday/domain/TravelogueDay.java
  backend/src/main/java/woowacourse/touroot/traveloguephoto/domain/TraveloguePhoto.java
  backend/src/main/java/woowacourse/touroot/travelogueplace/domain/TraveloguePlace.java
  backend/src/main/resources/application.yml
Labels: BE

#26 [Feature] - 여행기 관련 Entity Repository 생성
  backend/src/main/java/woowacourse/touroot/place/repository/PlaceRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/repository/TravelogueRepository.java
  backend/src/main/java/woowacourse/touroot/travelogueday/repository/TravelogueDayRepository.java
  backend/src/main/java/woowacourse/touroot/traveloguephoto/repository/TraveloguePhotoRepository.java
  backend/src/main/java/woowacourse/touroot/travelogueplace/repsitory/TraveloguePlaceRepository.java
Labels: BE

#28 [Feature] - 여행기 상세 조회 Service 생성
  backend/src/main/java/woowacourse/touroot/place/domain/Place.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/TravelogueResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueService.java
  backend/src/main/java/woowacourse/touroot/travelogueday/dto/TravelogueDayResponse.java
  backend/src/main/java/woowacourse/touroot/travelogueplace/dto/TraveloguePlaceResponse.java
Labels: BE

#29 [Feature] - local/dev profile 분리
  backend/Dockerfile
  backend/src/main/resources/application.yml
Labels: BE

#31 [Feature] - 여행기 상세 조회 Controller 생성
  backend/src/main/java/woowacourse/touroot/travelogue/controller/TravelogueController.java
Labels: BE

#33 [Feature] - self hosted runner 를 활용한 CD 구축
  .github/workflows/be-dev-ci.yml
Labels: BE

#35 [Fix] - CD deploy.sh 실행 경로 수정
  .github/workflows/be-dev-ci-cd.yml
Labels: BE

#39 [Fix] - CD docker compose up 수행 경로 수정
  .github/workflows/be-dev-ci-cd.yml
Labels: BE

#37 [Feature] - CORS 설정
  backend/src/main/java/woowacourse/touroot/global/config/WebConfig.java
Labels: BE

#41 [Feature] - PR을 생성 할 때 빌드 및 테스트 하는 CI Workflow 추가
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-ci.yml
Labels: BE

#44 [Feature] - JPA Auditing을 위한 BaseEntity 생성
  backend/src/main/java/woowacourse/touroot/TourootApplication.java
  backend/src/main/java/woowacourse/touroot/entity/BaseEntity.java
  backend/src/main/java/woowacourse/touroot/place/domain/Place.java
  backend/src/main/java/woowacourse/touroot/travelogue/day/domain/TravelogueDay.java
  backend/src/main/java/woowacourse/touroot/travelogue/day/dto/TravelogueDayResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/day/repository/TravelogueDayRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/TravelogueResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/photo/domain/TraveloguePhoto.java
  backend/src/main/java/woowacourse/touroot/travelogue/photo/repository/TraveloguePhotoRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/place/domain/TraveloguePlace.java
  backend/src/main/java/woowacourse/touroot/travelogue/place/dto/TraveloguePlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/place/repsitory/TraveloguePlaceRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueService.java
  backend/src/main/java/woowacourse/touroot/travelogueday/dto/TravelogueDayResponse.java
Labels: BE

#50 [Feature] - 여행 계획 작성 API 구현
  backend/src/main/java/woowacourse/touroot/global/exception/BadRequestException.java
  backend/src/main/java/woowacourse/touroot/place/domain/Place.java
  backend/src/main/java/woowacourse/touroot/place/repository/PlaceRepository.java
  backend/src/main/java/woowacourse/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/woowacourse/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/woowacourse/touroot/travelplan/domain/TravelPlanDay.java
  backend/src/main/java/woowacourse/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/PlanDayCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/PlanLocationCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/PlanPlaceCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/TravelPlanCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/TravelPlanCreateResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/repository/TravelPlanDayRepository.java
  backend/src/main/java/woowacourse/touroot/travelplan/repository/TravelPlanPlaceRepository.java
  backend/src/main/java/woowacourse/touroot/travelplan/repository/TravelPlanRepository.java
  backend/src/main/java/woowacourse/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/woowacourse/touroot/travelplan/domain/TravelPlanTest.java
Labels: BE

#51 [Feature] - stylelint 설정
  .vscode/extensions.json
  .vscode/settings.json
  frontend/.stylelintrc.json
  frontend/package.json
Labels: FE, chore

#42 [Feature] - 여행기 상세 기능 구현
  frontend/.gitignore
  frontend/.prettierrc.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/client.ts
  frontend/src/assets/fonts/woff-subset/Pretendard-Black.subset.woff
  frontend/src/assets/fonts/woff-subset/Pretendard-Bold.subset.woff
  frontend/src/assets/fonts/woff-subset/Pretendard-ExtraBold.subset.woff
  frontend/src/assets/fonts/woff-subset/Pretendard-ExtraLight.subset.woff
  frontend/src/assets/fonts/woff-subset/Pretendard-Light.subset.woff
  frontend/src/assets/fonts/woff-subset/Pretendard-Medium.subset.woff
  frontend/src/assets/fonts/woff-subset/Pretendard-Regular.subset.woff
  frontend/src/assets/fonts/woff-subset/Pretendard-SemiBold.subset.woff
  frontend/src/assets/fonts/woff-subset/Pretendard-Thin.subset.woff
  frontend/src/assets/svg/back-icon.svg
  frontend/src/assets/svg/down-arrow.svg
  frontend/src/assets/svg/empty-heart.svg
  frontend/src/assets/svg/hamburger.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/marker.svg
  frontend/src/assets/svg/next-arrow.svg
  frontend/src/assets/svg/prev-arrow.svg
  frontend/src/assets/svg/up-arrow.svg
  frontend/src/components/common/Box/Box.styled.ts
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Carousel/Carousel.styled.ts
  frontend/src/components/common/Carousel/Carousel.tsx
  frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/common/Tab/Tab.tsx
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/pages/index.ts
  frontend/src/components/pages/travelogueDetail/PlaceDetailCard/PlaceDetailCard.styled.ts
  frontend/src/components/pages/travelogueDetail/PlaceDetailCard/PlaceDetailCard.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/main.tsx
  frontend/src/styles/emotion.d.ts
  frontend/src/styles/fonts.d.ts
  frontend/src/styles/globalStyle.ts
  frontend/src/styles/svg.d.ts
  frontend/src/styles/theme.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: FE

#54 [Feature] - 여행기 상세 조회 로직 리팩토링
  backend/build.gradle
  backend/src/main/java/woowacourse/touroot/place/domain/Place.java
  backend/src/main/java/woowacourse/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/woowacourse/touroot/travelogue/day/dto/TravelogueDayResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/day/repository/TravelogueDayRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/day/domain/TravelogueDay.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/day/dto/TravelogueDayResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/day/repository/TravelogueDayRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/day/service/TravelogueDayService.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/photo/domain/TraveloguePhoto.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/photo/repository/TraveloguePhotoRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/photo/service/TraveloguePhotoService.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/place/domain/TraveloguePlace.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/place/dto/TraveloguePlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/place/repsitory/TraveloguePlaceRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/place/service/TraveloguePlaceService.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/TravelogueResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/photo/repository/TraveloguePhotoRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/place/dto/TraveloguePlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/place/repsitory/TraveloguePlaceRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/woowacourse/touroot/global/AcceptanceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/woowacourse/touroot/utils/DatabaseCleaner.java
  backend/src/test/java/woowacourse/touroot/utils/TestFixture.java
Labels: BE

#59 [Feature] - codeowner 및 자동 할당 설정
  .github/CODEOWNERS
Labels: FE, chore

#58 [Feature] - 테스트 환경 설정 추가
  frontend/.eslintrc.cjs
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/jest.config.js
  frontend/package.json
Labels: FE, chore

#56 [Feature] - 여행 계획 상세 조회 API 구현
  backend/src/main/java/woowacourse/touroot/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/woowacourse/touroot/global/exception/dto/ExceptionResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/woowacourse/touroot/travelplan/domain/TravelPlanDay.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanDayCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanLocationCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanPlaceCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/TravelPlanCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanCreateResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanDayResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanLocationResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanPlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/woowacourse/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/woowacourse/touroot/travelplan/service/TravelPlanServiceTest.java
  backend/src/test/java/woowacourse/touroot/utils/TestFixture.java
Labels: BE

#55 [Feature] - 카카오 로그인 구현
  backend/build.gradle
  backend/src/main/java/woowacourse/touroot/authentication/controller/LoginController.java
  backend/src/main/java/woowacourse/touroot/authentication/dto/KakaoAccessTokenResponse.java
  backend/src/main/java/woowacourse/touroot/authentication/dto/LoginResponse.java
  backend/src/main/java/woowacourse/touroot/authentication/dto/OauthUserInformationResponse.java
  backend/src/main/java/woowacourse/touroot/authentication/infrastructure/JwtTokenProvider.java
  backend/src/main/java/woowacourse/touroot/authentication/infrastructure/KakaoOauthClient.java
  backend/src/main/java/woowacourse/touroot/authentication/infrastructure/KakaoOauthProvider.java
  backend/src/main/java/woowacourse/touroot/authentication/service/LoginService.java
  backend/src/main/java/woowacourse/touroot/global/config/JasyptConfig.java
  backend/src/main/java/woowacourse/touroot/member/domain/Member.java
  backend/src/main/java/woowacourse/touroot/member/repository/MemberRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/woowacourse/touroot/TourootApplicationTests.java
  backend/src/test/java/woowacourse/touroot/global/AcceptanceTest.java
  backend/src/test/java/woowacourse/touroot/utils/DatabaseCleaner.java
  backend/src/test/java/woowacourse/touroot/utils/TestFixture.java
  backend/src/test/resources/application-test.yml
Labels: BE

#67 [Feature] - 여행 계획 코드 리팩토링
  backend/src/main/java/woowacourse/touroot/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanDayCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanPlaceCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/TravelPlanCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/woowacourse/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/woowacourse/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#61 [Feature] Storybook 배포 설정
  .github/workflows/chromatic.yml
  frontend/chromatic_publish.sh
  frontend/package.json
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.stories.tsx
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
  frontend/yarn.lock
Labels: FE

#71 [Feature] - react-router-dom 설정
  .github/workflows/chromatic.yml
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/chromatic_publish.sh
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.stories.tsx
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
  frontend/src/components/layout/AppLayout/AppLayout.styled.ts
  frontend/src/components/layout/AppLayout/AppLayout.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/constants/route.ts
  frontend/src/router.tsx
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: FE, chore

#76 [Feature] - 서비스 Foundation 설정
  frontend/package.json
  frontend/src/components/common/Box/Box.styled.ts
  frontend/src/components/common/Carousel/Carousel.styled.ts
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
  frontend/src/components/pages/travelogueDetail/PlaceDetailCard/PlaceDetailCard.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/styles/emotion.d.ts
  frontend/src/styles/globalStyle.ts
  frontend/src/styles/theme.ts
  frontend/src/styles/tokens/colors.ts
  frontend/src/styles/tokens/index.ts
  frontend/src/styles/tokens/spacing.ts
  frontend/src/styles/tokens/typography.ts
  frontend/src/types/style/emotion.d.ts
  frontend/src/types/style/fonts.d.ts
  frontend/src/types/style/svg.d.ts
Labels: FE, chore

#73 [Feature] - msw 설정
  frontend/.prettierrc.json
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/jest-setup.ts
  frontend/jest.config.js
  frontend/jest.polyfills.js
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/server.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: FE, chore

#68 [Feature] - 여행기 작성 API 및 여행기 전체 조회 API 구현
  backend/src/main/java/woowacourse/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/TravelogueDay.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/TraveloguePhoto.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/day/dto/TravelogueDayResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/day/service/TravelogueDayService.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/photo/service/TraveloguePhotoService.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/place/dto/TraveloguePlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/place/service/TraveloguePlaceService.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TravelogueDayRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TravelogueLocationRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePhotoRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TravelogueDayResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TravelogueLocationResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TraveloguePlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TravelogueResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/repository/TravelogueDayRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/repository/TraveloguePhotoRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/repository/TraveloguePlaceRepository.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueDayService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePhotoService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/woowacourse/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/woowacourse/touroot/utils/TestFixture.java
Labels: BE

#85 [Fix] - CI xml 파일 미인식 문제 및 요청 초과로 인한 액션 실패 해결
  .github/workflows/be-ci.yml
Labels: BE

#84 [Feature] - 인증과정 예외처리
  backend/src/main/java/woowacourse/touroot/authentication/controller/LoginController.java
  backend/src/main/java/woowacourse/touroot/authentication/dto/LoginResponse.java
  backend/src/main/java/woowacourse/touroot/authentication/infrastructure/KakaoOauthClient.java
  backend/src/main/java/woowacourse/touroot/authentication/service/LoginService.java
  backend/src/main/java/woowacourse/touroot/global/exception/ClientException.java
  backend/src/main/java/woowacourse/touroot/global/exception/GlobalExceptionHandler.java
Labels: BE

#90 [Feature] - 여행기 등록 페이지에 필요한 공통 컴포넌트 구현(시모)
  frontend/.storybook/preview.tsx
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/tturi.svg
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/CharacterCount/CharacterCount.styled.ts
  frontend/src/components/common/CharacterCount/CharacterCount.tsx
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/ModalBottomSheet/BackDrop/BackDrop.styled.ts
  frontend/src/components/common/ModalBottomSheet/BackDrop/BackDrop.tsx
  frontend/src/components/common/ModalBottomSheet/Container/Container.styled.ts
  frontend/src/components/common/ModalBottomSheet/Container/Container.tsx
  frontend/src/components/common/ModalBottomSheet/Content/Content.styled.ts
  frontend/src/components/common/ModalBottomSheet/Content/Content.tsx
  frontend/src/components/common/ModalBottomSheet/Footer/Footer.styled.ts
  frontend/src/components/common/ModalBottomSheet/Footer/Footer.tsx
  frontend/src/components/common/ModalBottomSheet/Header/Header.styled.ts
  frontend/src/components/common/ModalBottomSheet/Header/Header.tsx
  frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.stories.tsx
  frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.tsx
  frontend/src/components/common/Textarea/Textarea.stories.tsx
  frontend/src/components/common/Textarea/Textarea.styled.ts
  frontend/src/components/common/Textarea/Textarea.tsx
  frontend/tsconfig.json
Labels: FE

#89 [Feature] - 여행기 등록 페이지에 필요한 공통 컴포넌트 구현(리버)
  frontend/src/assets/svg/camera-icon.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/picture-icon.svg
  frontend/src/assets/svg/x-icon.svg
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.stories.tsx
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.styled.ts
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.stories.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.styled.ts
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.tsx
  frontend/src/components/hooks/useDragScroll.ts
  frontend/src/components/hooks/useImageUpload.ts
Labels: FE

#93 [Feature] - dev profile https
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-ci.yml
  backend/src/main/resources/application.yml
Labels: BE

#99 [Feature] - 여행기 관련 테스트 작성 및 리팩토링
  backend/src/main/java/woowacourse/touroot/PingController.java
  backend/src/main/java/woowacourse/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/TraveloguePhoto.java
  backend/src/main/java/woowacourse/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueDayService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePhotoService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/woowacourse/touroot/global/ServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueTestFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelplan/service/TravelPlanServiceTest.java
  backend/src/test/java/woowacourse/touroot/utils/TestFixture.java
Labels: BE

#103 [Refactor] - 여행기 응답 DTO 속성 이름 변경
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePositionRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TraveloguePlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TraveloguePositionResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueTestFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePlaceServiceTest.java
Labels: BE

#102 [Refactor] - 여행 계획 양방향 의존 제거 및 리팩토링
  backend/src/main/java/woowacourse/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/woowacourse/touroot/travelplan/domain/TravelPlanDay.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanPlaceCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/request/PlanPositionCreateRequest.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanPlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/dto/response/TravelPlanPositionResponse.java
  backend/src/main/java/woowacourse/touroot/travelplan/repository/TravelPlanDayRepository.java
  backend/src/main/java/woowacourse/touroot/travelplan/repository/TravelPlanPlaceRepository.java
  backend/src/main/java/woowacourse/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/woowacourse/touroot/global/ServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/woowacourse/touroot/travelplan/helper/TravelPlanTestHelper.java
  backend/src/test/java/woowacourse/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#106 [Refactor] - 여행기 작성 요청 DTO 필드 이름 변경
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePhotoRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePlaceServiceTest.java
Labels: BE

#108 [Feature] - FE develop CORS 처리
  backend/src/main/java/woowacourse/touroot/global/config/WebConfig.java
Labels: BE

#109 [Feature] - FE develop CORS 처리
  backend/src/main/java/woowacourse/touroot/global/config/WebConfig.java
Labels: BE

#112 [Fix] - 이미지 저장 api 반환 값 변경
  backend/src/main/java/woowacourse/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application-test.yml
Labels: BE

#114 [Fix] - 업로드한 이미지 url에 접속하면 이미지를 열지 않고 다운로드 받는 버그 해결
  backend/src/main/java/woowacourse/touroot/image/infrastructure/AwsS3Provider.java
Labels: BE

#115 [Feature] - 여행기 등록 기능 구현
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/src/components/common/Accordion/AccordionRoot/AccordionRoot.tsx
  frontend/src/components/common/DayContent/DayContent.tsx
  frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.tsx
  frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.styled.ts
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/ModalBottomSheet/Container/Container.styled.ts
  frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.tsx
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.tsx
  frontend/src/components/common/PageInfo/PageInfo.stories.tsx
  frontend/src/components/common/PageInfo/PageInfo.styled.ts
  frontend/src/components/common/PageInfo/PageInfo.tsx
  frontend/src/components/common/PageInfo/PageInfo.type.ts
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.styled.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/route.ts
  frontend/src/hooks/index.ts
  frontend/src/hooks/pages/useTravelDays.ts
  frontend/src/hooks/useDragScroll.ts
  frontend/src/hooks/useImageUpload.ts
  frontend/src/queries/index.ts
  frontend/src/queries/usePostTravelogue/usePostTravelogue.ts
  frontend/src/queries/usePostUploadImages/usePostUploadImages.ts
  frontend/src/router.tsx
  frontend/src/types/domain/travelogue.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: FE

#119 [Refactor] 여행기, 여행계획 DTO에 사용되는 도메인 용어 통일 개선
  backend/src/main/java/woowacourse/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/woowacourse/touroot/travelogue/dto/response/TraveloguePlaceResponse.java
  backend/src/main/java/woowacourse/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueTestFixture.java
Labels: BE

#121 [Fix] Kakao Redirect Uri 서버 엔드포인트에서 랜딩 페이지로 수정
  backend/src/main/resources/application.yml
Labels: BE

#123 [Fix] Kakao Oauth 카카오 로그인 api 명세 수정
  backend/src/main/java/woowacourse/touroot/authentication/controller/LoginController.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application-test.yml
Labels: BE

#80 [Feature] - 로그인 페이지 구현
  frontend/.stylelintrc.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/kakao-symbol.svg
  frontend/src/assets/webp/excitedTturi.webp
  frontend/src/assets/webp/index.ts
  frontend/src/components/common/Box/Box.styled.ts
  frontend/src/components/common/Carousel/Carousel.styled.ts
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
  frontend/src/components/pages/login/KakaoCallbackPage.tsx
  frontend/src/components/pages/login/LoginPage.styled.ts
  frontend/src/components/pages/login/LoginPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/constants/route.ts
  frontend/src/router.tsx
  frontend/src/styles/emotion.d.ts
  frontend/src/styles/globalStyle.ts
  frontend/src/styles/webp.d.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: FE 📺

#125 [Feature] - 여행 계획 등록 페이지 구현
  frontend/package.json
  frontend/src/components/common/DateRangePicker/DateRangePicker.tsx
  frontend/src/components/common/DayContent/DayContent.tsx
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/route.ts
  frontend/src/hooks/pages/useTravelDays.ts
  frontend/src/main.tsx
  frontend/src/queries/usePostTravelPlan/usePostTravelPlan.ts
  frontend/src/router.tsx
  frontend/src/types/domain/travelogue.ts
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: FE 📺

#78 [Feature] - 메인 페이지 구현
  frontend/src/App.tsx
  frontend/src/assets/svg/default-avatar.svg
  frontend/src/assets/svg/double-right-arrow.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/common/AvatarCircle/AvatarCircle.stories.tsx
  frontend/src/components/common/AvatarCircle/AvatarCircle.styled.ts
  frontend/src/components/common/AvatarCircle/AvatarCircle.tsx
  frontend/src/components/common/AvatarCircle/AvatarCircle.type.ts
  frontend/src/components/common/Drawer/Drawer.stories.tsx
  frontend/src/components/common/Drawer/Drawer.styled.ts
  frontend/src/components/common/Drawer/Drawer.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/pages/main/MainPage.styled.ts
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.stories.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.styled.ts
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/hooks/useImageError.ts
  frontend/src/hooks/useIntersectionObserver.ts
  frontend/src/queries/useInfiniteTravelogues.ts
  frontend/src/types/index.ts
Labels: FE 📺

#127 [Feature] - 여행 계획 상세조회 페이지 구현
  frontend/.storybook/preview.tsx
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.stories.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.stories.tsx
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.tsx
  frontend/src/components/pages/Da.tsx
  frontend/src/components/pages/TravelPlansDetail/TravelPlansDetail.styled.ts
  frontend/src/components/pages/TravelPlansDetail/TravelPlansDetail.tsx
  frontend/src/components/pages/TravelPlansDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts
  frontend/src/components/pages/TravelPlansDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/queries/useRegisterTravelogue/useRegisterTravelogue.ts
Labels: FE 📺

#126 [Feature] - Github action gradle 캐싱 도입
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-ci.yml
Labels: BE 🍃

#129 [Refactor] - Test fixture를 Enum으로 리팩토링
  backend/src/test/java/woowacourse/touroot/place/fixture/PlaceFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueDayFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TraveloguePhotoFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TraveloguePlaceFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueRequestFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/fixture/TravelogueTestFixture.java
  backend/src/test/java/woowacourse/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE

#132 [Feature] 카카오 로그인 Redirect Uri 프론트 배포 주소로 변경
  backend/src/main/resources/application.yml
Labels: BE

#134 [Fix] - 업로드 이미지 용량 조정
  backend/src/main/java/woowacourse/touroot/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application.yml
Labels: BE

#136 [Fix] - Spring Boot Timezone KST로 설정
  backend/Dockerfile
Labels: BE

#138 [Fix] - HEIC 이미지 파일 확장자 허용
  backend/src/main/java/woowacourse/touroot/image/domain/ImageFile.java
Labels: BE

#117 [Feature] - chromatic 배포 yml 파일 추가
  .github/workflows/chromatic.yml
Labels: FE, INFRA ⚙️

#66 [Feature] - CI 설정
  .github/workflows/frontend-ci.yml
  frontend/jest.config.js
  frontend/package.json
  frontend/src/components/common/Carousel/Carousel.styled.ts
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
Labels: FE, INFRA ⚙️

#144 [Feature] - 프론트 로컬 개발을 위한 Oauth redirect uri 수정
  backend/src/main/resources/application.yml
Labels: BE

#145 [Feature] - 3주차 스프린트 리팩토링
  frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.styled.ts
  frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.tsx
  frontend/src/components/common/FloatingButton/FloatingButton.styled.ts
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.styled.ts
  frontend/yarn.lock
Labels: FE

#79 [Feature] - 인가 구현
  backend/src/main/java/woowacourse/touroot/authentication/infrastructure/JwtTokenProvider.java
  backend/src/main/java/woowacourse/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/woowacourse/touroot/global/auth/MemberAuthMethodArgumentResolver.java
  backend/src/main/java/woowacourse/touroot/global/auth/dto/HttpRequestInfo.java
  backend/src/main/java/woowacourse/touroot/global/auth/dto/MemberAuth.java
  backend/src/main/java/woowacourse/touroot/global/config/SwaggerConfig.java
  backend/src/main/java/woowacourse/touroot/global/config/WebMvcConfig.java
  backend/src/main/java/woowacourse/touroot/global/exception/UnauthorizedException.java
  backend/src/test/java/woowacourse/touroot/authentication/controller/LoginControllerTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/woowacourse/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/woowacourse/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/woowacourse/touroot/travelplan/helper/TravelPlanTestHelper.java
Labels: BE

#155 [Fix] - AuthFilter WhiteList 로그인 get -> post로 변경
  backend/src/main/java/woowacourse/touroot/global/auth/JwtAuthFilter.java
Labels: BE

#156 [Fix] - Authorization 오류 해결
  backend/src/main/java/woowacourse/touroot/global/config/WebConfig.java
Labels: BE

#150 [Fix] - ci 에러 해결
  .github/workflows/frontend-ci.yml
Labels: FE

#163 [Fix] - SSL key-store-password 변경
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/resources/application.yml
Labels: BE

#168 [Feature] - sentry 세팅하기
  frontend/package.json
  frontend/src/apis/ApiError.ts
  frontend/src/main.tsx
  frontend/src/queries/useGetTravelogue.ts
  frontend/yarn.lock
Labels: FE

#164 [Feature] - 2차 스프린트 리팩토링
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/ModalBottomSheet/BackDrop/BackDrop.styled.ts
  frontend/src/components/common/ModalBottomSheet/Container/Container.styled.ts
  frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.tsx
  frontend/src/hooks/useBottomSheet.ts
  frontend/src/styles/globalStyle.ts
Labels: FE

#170 [Feature] - 로그인 명세 수정 개선
  backend/src/main/java/kr/touroot/authentication/controller/LoginController.java
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/resources/application.yml
Labels: BE

#173 [Fix] - CORS config에서 allowedHeaders 제거
  backend/.gitignore
  backend/src/main/java/kr/touroot/global/config/WebConfig.java
Labels: BE
