Repository woowacourse-teams/2024-touroot, pull requests merged in 2024-09, with the labels that each got.

#412 [Feature] - e2e 테스트 초기 설정 및 여행 계획 등록, 로그인, 메인 페이지 e2e 테스트 구현
  .github/workflows/frontend-ci-development.yml
  frontend/.eslintrc.cjs
  frontend/cypress.config.ts
  frontend/cypress/cypress.d.ts
  frontend/cypress/e2e/login.cy.ts
  frontend/cypress/e2e/mainPage.cy.ts
  frontend/cypress/e2e/travelPlanRegister.cy.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/tsconfig.json
  frontend/package.json
  frontend/src/components/common/Accordion/AccordionItem/AccordionItem.tsx
  frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.tsx
  frontend/src/components/common/Calendar/Calendar.tsx
  frontend/src/components/common/Chip/Chip.tsx
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanDayAccordion/TravelPlanDayAccordion.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/constants/cypress.ts
  frontend/src/utils/cypress.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: FE, TEST 🧪

#414 [Feature] - 여행 계획 등록 페이지 리팩터링
  frontend/package.json
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelPlanForm.ts
  frontend/yarn.lock
Labels: FE, REFACTOR ♻️

#396 [Feature] - 엔티티 테이블 인덱스 명세 작성
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/place/domain/Place.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
Labels: BE

#423 [Refactor] - 역방향 참조 필요한 엔티티 양방향 연관관계로 개선
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueDay.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanDay.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
Labels: BE, REFACTOR ♻️

#425 [Feature] - Spring Actuator 도입
  backend/build.gradle
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/resources/application.yml
Labels: BE, INFRA ⚙️

#427 [Fix] - Spring Actuator 접속 불가 문제 해결
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/static/favicon.ico
  backend/src/test/resources/application-test.yml
Labels: BE, INFRA ⚙️

#431 [Feature] - 프로덕션 api-v1.0.0 배포
  .github/workflows/be-cd-dev.yml
  backend/build.gradle
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/place/domain/Place.java
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueDay.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanDay.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/static/favicon.ico
  backend/src/test/resources/application-test.yml
Labels: BE

#429 [Fix] - 다운로드 된 폰트를 불러오지 않는 문제 해결
  frontend/src/styles/globalStyle.ts
Labels: FE

#430 [Feature] - kakao bundle lazy loading 적용
  frontend/public/index.html
Labels: FE

#441 [Refactor] - RDS reader, writer 엔드포인트 연결 쓰기 작업, 읽기 작업 분리 검토
  backend/src/main/java/kr/touroot/authentication/service/LoginService.java
  backend/src/main/java/kr/touroot/global/config/DataSourceConfig.java
  backend/src/main/java/kr/touroot/global/config/DynamicRoutingDataSource.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/main/resources/application.yml
Labels: BE, REFACTOR ♻️

#440 [Feature] - 사용자 이름 기준 여행기 조회 기능 구현
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/SearchCondition.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/SearchType.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueSearchRequest.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE

#449 [Feature] - DB 스키마 형상관리를 위한 Flyway 도입 BE
  backend/build.gradle
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/mysql/V1__init.sql
  backend/src/test/resources/application-test.yml
Labels: BE

#418 [Feature] - 데모데이 피드백 반영(지니)
  frontend/cypress/e2e/travelPlanRegister.cy.ts
  frontend/package.json
  frontend/src/components/common/Calendar/Calendar.styled.ts
  frontend/src/components/common/Calendar/Calendar.tsx
  frontend/src/components/common/GoogleMapView/GoogleMapView.constant.ts
  frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
  frontend/src/components/common/GoogleMapView/GoogleMapView.util.ts
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/hooks/useGoogleMap.ts
Labels: FE

#443 [Refactor] - Place 엔티티 역정규화
  backend/src/main/java/kr/touroot/place/domain/Place.java
  backend/src/main/java/kr/touroot/place/repository/PlaceRepository.java
  backend/src/main/java/kr/touroot/position/domain/Position.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TraveloguePlaceResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TraveloguePositionResponse.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPlaceResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPositionResponse.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/main/resources/db/migration/mysql/V1__init.sql
  backend/src/main/resources/db/migration/mysql/V2__delete_place.sql
  backend/src/test/java/kr/touroot/coordinate/domain/PositionTest.java
  backend/src/test/java/kr/touroot/place/domain/PlaceTest.java
  backend/src/test/java/kr/touroot/place/fixture/PlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePlaceTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanPlaceFixture.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
Labels: BE, REFACTOR ♻️

#457 [Fix] - Flyway Migration Fail 버그 해결
  backend/src/main/resources/db/migration/mysql/V2__delete_place.sql
Labels: BE, INFRA ⚙️

#447 [Feature] - webpack 캐시 버스팅 설정
  frontend/webpack.common.js
  frontend/webpack.production.js
Labels: FE

#450 [Feature] - 코드 스플리팅 설정
  frontend/package.json
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/components/common/index.ts
  frontend/src/router.tsx
  frontend/webpack.production.js
  frontend/yarn.lock
Labels: FE, REFACTOR ♻️

#453 [Feature] - 여행 계획 상세 페이지 성능 최적화
  frontend/public/index.html
  frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.constants.ts
  frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
Labels: FE, REFACTOR ♻️

#454 [Feature] - Layout Shift 개선
  frontend/src/components/common/Accordion/AccordionRoot/AccordionRoot.styled.ts
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/pages/my/MyPage.styled.ts
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.styled.ts
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.styled.ts
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.styled.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
Labels: FE, REFACTOR ♻️

#455 [Feature] - 이미지 최적화
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/resize.ts
  frontend/src/utils/resizeAndConvertImage.ts
Labels: FE

#458 [Feature] - touroot v1.1.0
  .github/workflows/frontend-ci-development.yml
  frontend/.eslintrc.cjs
  frontend/cypress.config.ts
  frontend/cypress/cypress.d.ts
  frontend/cypress/e2e/login.cy.ts
  frontend/cypress/e2e/mainPage.cy.ts
  frontend/cypress/e2e/travelPlanRegister.cy.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/tsconfig.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/common/Accordion/AccordionItem/AccordionItem.tsx
  frontend/src/components/common/Accordion/AccordionRoot/AccordionRoot.styled.ts
  frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.tsx
  frontend/src/components/common/Calendar/Calendar.styled.ts
  frontend/src/components/common/Calendar/Calendar.tsx
  frontend/src/components/common/Chip/Chip.tsx
  frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.constants.ts
  frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.tsx
  frontend/src/components/common/GoogleMapView/GoogleMapView.constant.ts
  frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
  frontend/src/components/common/GoogleMapView/GoogleMapView.util.ts
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.tsx
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/my/MyPage.styled.ts
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.styled.ts
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanDayAccordion/TravelPlanDayAccordion.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.styled.ts
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.styled.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/cypress.ts
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/resize.ts
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelPlanForm.ts
  frontend/src/hooks/useGoogleMap.ts
  frontend/src/router.tsx
  frontend/src/styles/globalStyle.ts
  frontend/src/utils/cypress.ts
  frontend/src/utils/resizeAndConvertImage.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.production.js
  frontend/yarn.lock
Labels: FE

#444 [Feature] - 데모데이 피드백 반영(리버)
  frontend/src/apis/interceptor.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/pages/search/SearchPage.styled.ts
  frontend/src/components/pages/search/SearchPage.tsx
  frontend/src/components/pages/search/TravelogueList/TravelogueList.styled.ts
  frontend/src/components/pages/search/TravelogueList/TravelogueList.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.stories.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/pages/useTravelPlanForm.ts
  frontend/src/hooks/usePreviousPage.ts
  frontend/src/queries/useInfiniteSearchTravelogues.ts
  frontend/src/types/domain/travelogue.ts
  frontend/src/utils/getDaysAndNights.ts
  frontend/src/utils/getInitialTravelTitle.ts
Labels: FE, REFACTOR ♻️

#460 [Fix] - 테그 필터링 스크롤 끝까지 되지 않는 문제 해결
  frontend/src/components/pages/main/MainPage.styled.ts
Labels: FE, REFACTOR ♻️

#462 [Fix] - 검색 페이지 탭바 width 수정, 여행기 수정페이지에서 이미지 최적화 안됨
  frontend/src/components/pages/search/SearchPage.styled.ts
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
Labels: FE

#465 [Fix] - 검색 초기 페이지로 접근 시 에러가 발생하는 문제 수정
  frontend/src/router.tsx
Labels: FE

#471 [Fix] - develop S3 원본 경로 검증 url 변경
  backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application-test.yml
Labels: BE, INFRA ⚙️

#473 [Fix] - NotFound의 버튼 텍스트가 잘못된 부분 수정
  frontend/src/components/pages/notFound/NotFoundPage.tsx
Labels: FE

#476 [Refactor] - Flyway 마이그레이션 단계 세분화(그런데 이제 안전한 마이그레이션 플랜을 곁들인...)
  backend/src/main/java/kr/touroot/place/domain/Place.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/resources/db/migration/mysql/V2__add_travelogue_like_count.sql
  backend/src/main/resources/db/migration/mysql/V2__delete_place.sql
  backend/src/main/resources/db/migration/mysql/V3.0__add_place_column.sql
  backend/src/main/resources/db/migration/mysql/V3.1__migrate_place_rows.sql
  backend/src/main/resources/db/migration/mysql/V3.2__migrate_remaining_place.sql
  backend/src/main/resources/db/migration/mysql/V3.3__add_not_null_constaint.sql
  backend/src/main/resources/db/migration/mysql/V4__add_like_count_index.sql
Labels: BE, REFACTOR ♻️

#481 [Feature] - 프로덕션 api-v1.1.0 배포
  backend/build.gradle
  backend/src/main/java/kr/touroot/authentication/service/LoginService.java
  backend/src/main/java/kr/touroot/global/config/DataSourceConfig.java
  backend/src/main/java/kr/touroot/global/config/DynamicRoutingDataSource.java
  backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/main/java/kr/touroot/place/repository/PlaceRepository.java
  backend/src/main/java/kr/touroot/position/domain/Position.java
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueFilterCondition.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/SearchCondition.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/SearchType.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueFilterRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueSearchRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TraveloguePlaceResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TraveloguePositionResponse.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPlaceResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPositionResponse.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/mysql/V1__init.sql
  backend/src/main/resources/db/migration/mysql/V2__add_travelogue_like_count.sql
  backend/src/main/resources/db/migration/mysql/V3.0__add_place_column.sql
  backend/src/main/resources/db/migration/mysql/V3.1__migrate_place_rows.sql
  backend/src/main/resources/db/migration/mysql/V3.2__migrate_remaining_place.sql
  backend/src/main/resources/db/migration/mysql/V3.3__add_not_null_constaint.sql
  backend/src/main/resources/db/migration/mysql/V4__add_like_count_index.sql
  backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java
  backend/src/test/java/kr/touroot/coordinate/domain/PositionTest.java
  backend/src/test/java/kr/touroot/place/domain/PlaceTest.java
  backend/src/test/java/kr/touroot/place/fixture/PlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePlaceTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanPlaceFixture.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
  backend/src/test/resources/application-test.yml
Labels: BE

#483 [Fix] - place_id NOT NULL 제약 조건 삭제
  backend/src/main/resources/db/migration/mysql/V5__delete_place_id_not_null_constraint.sql
Labels: BE

#484 [Feature] - 프로덕션 api-v1.1.1 배포
  backend/src/main/resources/db/migration/mysql/V5__delete_place_id_not_null_constraint.sql
Labels: BE

#478 [Fix] - 상세보기에서 좋아요 누를 때마다 지도 움직이는 문제 & 사용자가 지도를 확대하지 못하는 문제 해결
  frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
  frontend/src/hooks/useGoogleMap.ts
Labels: FE

#479 [Fix] - 5차 스프린트 QA 반영 1차 (리버)
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/SearchHeader/SearchHeader.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/pages/main/MainPage.constants.ts
  frontend/src/components/pages/search/SearchPage.styled.ts
  frontend/src/components/pages/search/SearchPage.tsx
  frontend/src/components/pages/search/TravelogueList/TravelogueList.styled.ts
  frontend/src/components/pages/search/TravelogueList/TravelogueList.tsx
Labels: FE, REFACTOR ♻️
