Repository woowacourse-teams/2024-touroot, pull requests merged in 2024-08, with the labels that each got.

#178 [Feature] - 여행 계획 도메인쪽 인가 적용
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/global/auth/MemberAuthMethodArgumentResolver.java
  backend/src/main/java/kr/touroot/global/auth/dto/HttpRequestInfo.java
  backend/src/main/java/kr/touroot/global/auth/dto/MemberAuth.java
  backend/src/main/java/kr/touroot/global/exception/ForbiddenException.java
  backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/TravelPlanCreateRequest.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#177 [Feature] - 로깅 프레임워크 적용
  backend/.gitignore
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/global/auth/MemberAuthMethodArgumentResolver.java
  backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/kr/touroot/global/logging/LoggingFilter.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: BE

#175 [Feature] - 로그인 한 사용자만 여행기를 작성할 수 있도록 리팩토링
  backend/build.gradle
  backend/src/main/java/kr/touroot/authentication/infrastructure/JwtTokenProvider.java
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/global/auth/MemberAuthMethodArgumentResolver.java
  backend/src/main/java/kr/touroot/global/auth/dto/MemberAuth.java
  backend/src/main/java/kr/touroot/global/exception/UnauthorizedException.java
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE, REFACTOR ♻️

#146 [Feature] - 전환 기능 구현
  frontend/.storybook/main.ts
  frontend/jest.config.js
  frontend/src/App.tsx
  frontend/src/components/common/DayContent/DayContent.tsx
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/contexts/TravelTransformDetailProvider.tsx
  frontend/src/contexts/UserProvider.tsx
  frontend/src/hooks/pages/useTravelDays.ts
  frontend/src/hooks/useUser.ts
  frontend/src/queries/useGetTravelogue.ts
  frontend/src/queries/usePostTravelPlan.ts
  frontend/src/queries/usePostTravelogue.ts
  frontend/src/router.tsx
  frontend/src/types/domain/travelTransform.ts
  frontend/src/utils/object.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: FE

#176 [Feature] - 인가 처리 추가
  frontend/src/apis/ApiError.ts
  frontend/src/apis/client.ts
  frontend/src/apis/interceptor.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/main.tsx
  frontend/src/queries/useGetTravelPlan.ts
  frontend/src/queries/usePostTravelPlan.ts
  frontend/src/queries/usePostTravelogue.ts
  frontend/src/queries/usePostUploadImages.ts
  frontend/src/types/api/errorResponse.ts
Labels: FE

#179 [Feature] - 여행기, 여행계획 도메인 검증 규칙 추가 및 테스트 작성
  backend/src/main/java/kr/touroot/authentication/dto/response/LoginResponse.java
  backend/src/main/java/kr/touroot/global/config/WebConfig.java
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/place/domain/Place.java
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueDay.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePhoto.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePhotoRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePositionRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanDay.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java
  backend/src/test/java/kr/touroot/authentication/fixture/MemberFixture.java
  backend/src/test/java/kr/touroot/authentication/fixture/OauthUserInformationFixture.java
  backend/src/test/java/kr/touroot/member/domain/MemberTest.java
  backend/src/test/java/kr/touroot/place/domain/PlaceTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueDayTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePhotoTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePlaceTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueTest.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanDayTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanDayFixture.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanFixture.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
Labels: BE

#184 [Feature] - loggback console appender에 색상 추가
  backend/src/main/resources/logback-spring.xml
Labels: BE

#183 [Feature] - 사용하지 않는 S3 이미지 관리 기능 구현
  backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePhotoRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/kr/touroot/image/infrastructure/AwsS3ProviderTest.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePhotoFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/resources/application-test.yml
Labels: BE

#190 [Fix] - 썸네일 이미지 S3 영구 폴더 복사 기능 구현
  backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE

#188 [Feature] - 상수화 작업 진행
  frontend/src/apis/ApiError.ts
  frontend/src/apis/interceptor.ts
  frontend/src/components/common/Accordion/AccordionItem/accordionItemContext.ts
  frontend/src/components/common/Accordion/AccordionRoot/accordionContext.ts
  frontend/src/components/common/Drawer/Drawer.tsx
  frontend/src/components/common/FloatingButton/FloatingButton.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/pages/login/KakaoCallbackPage.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/endpoint.ts
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/httpStatusCode.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/route.ts
  frontend/src/constants/storage.ts
  frontend/src/contexts/TravelTransformDetailProvider.tsx
  frontend/src/contexts/UserProvider.tsx
  frontend/src/hooks/useUser.ts
  frontend/src/queries/useGetTravelPlan.ts
  frontend/src/queries/useGetTravelogue.ts
  frontend/src/queries/useInfiniteTravelogues.ts
  frontend/src/queries/usePostTravelPlan.ts
  frontend/src/queries/usePostTravelogue.ts
  frontend/src/queries/usePostUploadImages.ts
  frontend/src/router.tsx
Labels: FE, REFACTOR ♻️

#195 [Feature] - 마이 페이지 API 구현
  backend/src/main/java/kr/touroot/global/auth/dto/MemberAuth.java
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
  backend/src/main/java/kr/touroot/member/dto/MyTravelPlanResponse.java
  backend/src/main/java/kr/touroot/member/dto/MyTraveloguesResponse.java
  backend/src/main/java/kr/touroot/member/dto/ProfileResponse.java
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanRepository.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#191 [Feature] - 타입 구조 변경
  frontend/src/apis/interceptor.ts
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanDayAccordion/TravelPlanDayAccordion.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueDayAccordion/TravelogueDayAccordion.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/contexts/UserProvider.tsx
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelogueDays.ts
  frontend/src/queries/useGetTravelPlan.ts
  frontend/src/queries/useGetTravelogue.ts
  frontend/src/queries/usePostTravelPlan.ts
  frontend/src/queries/usePostTravelogue.ts
  frontend/src/types/domain/common.ts
  frontend/src/types/domain/travelPlan.ts
  frontend/src/types/domain/travelTransform.ts
  frontend/src/types/domain/travelogue.ts
  frontend/src/types/domain/user.ts
Labels: FE, REFACTOR ♻️

#166 [Feature] - 여행기 무한 스크롤 관련 테스트 추가
  frontend/.prettierrc.json
  frontend/__tests__/mainPage.test.tsx
  frontend/__tests__/utils/createInfiniteTravelogueHook.tsx
  frontend/jest.config.js
  frontend/src/mocks/data/travelogue.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/travelogueInfiniteHandler.ts
Labels: FE, TEST 🧪

#200 [Feature] - 모달 컴포넌트 구현
  frontend/src/assets/svg/index.ts
  frontend/src/components/common/Icon/svg-icons.json
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.style.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/ModalBody/ModalBody.styled.ts
  frontend/src/components/common/Modal/ModalBody/ModalBody.tsx
  frontend/src/components/common/Modal/ModalFooter/ModalFooter.styled.ts
  frontend/src/components/common/Modal/ModalFooter/ModalFooter.tsx
  frontend/src/components/common/Modal/ModalHeader/ModalHeader.styled.ts
  frontend/src/components/common/Modal/ModalHeader/ModalHeader.tsx
  frontend/src/contexts/ModalProvider.tsx
  frontend/src/hooks/useModalControl.ts
  frontend/src/hooks/usePressESC.ts
Labels: FE

#203 [Feature] - 여행 계획 공유 기능 구현
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/TravelPlanCreateRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanCreateResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanPlaceResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanPositionResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanResponse.java
  backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanRepository.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanFixture.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#212 [Fix] - 여행계획이 저장되지 않는 문제 해결UUID
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
Labels: BE

#213 [Fix] - DB 커넥션 인코딩 파라미터 지정
  backend/src/main/resources/application.yml
Labels: BE

#214 [Fix] - 데이터베이스 url 원복
  backend/src/main/resources/application.yml
Labels: BE

#207 [Fix] - 여행 전환 후 다른 페이지에서 다시 등록 페이지로 접근 시 데이터가 남아있는 문제 해결
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/contexts/TravelTransformDetailProvider.tsx
Labels: FE

#210 [Fix] - 등록 페이지에서 제목과 여행 장소 설명란 한글 입력시 제한 길이보다 1자 더 입력되는 문제 해결
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelogueDays.ts
Labels: FE

#220 [Fix] - 여행 계획 UUID 하이버네이트 매핑 타입과 같도록 수정
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
Labels: BE

#202 [Feature] - 로그인 명세 수정
  backend/src/main/java/kr/touroot/authentication/controller/LoginController.java
  backend/src/main/java/kr/touroot/authentication/infrastructure/KakaoOauthClient.java
  backend/src/main/java/kr/touroot/authentication/infrastructure/KakaoOauthProvider.java
  backend/src/main/java/kr/touroot/authentication/service/LoginService.java
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/resources/application.yml
  backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java
  backend/src/test/java/kr/touroot/authentication/service/LoginServiceTest.java
Labels: BE

#181 [Feature] - Login 명세 변경
  frontend/src/components/pages/login/KakaoCallbackPage.tsx
  frontend/src/constants/endpoint.ts
Labels: FE

#218 [Feature] - 마이페이지 API Swagger 작업
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
Labels: BE

#231 [Feature] - 마이페이지 내 여행기 조회 응답 수정
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
  backend/src/main/java/kr/touroot/member/dto/MyTraveloguesResponse.java
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
Labels: BE

#233 [Feature] - 마이 페이지 내 여행 계획 응답 변경
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
  backend/src/main/java/kr/touroot/member/dto/MyTravelogueResponse.java
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
Labels: BE

#221 [Feature] - 메인페이지 skeleton 작업
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/main/TravelogueCard/skeleton/TravelogueCardSkeleton.stories.tsx
  frontend/src/components/pages/main/TravelogueCard/skeleton/TravelogueCardSkeleton.styled.ts
  frontend/src/components/pages/main/TravelogueCard/skeleton/TravelogueCardSkeleton.tsx
  frontend/src/styles/tokens/colors.ts
Labels: FE

#222 [Feature] - Drawer가 열려져있는 경우 화면 스크롤 안되도록 수정
  frontend/src/components/common/Drawer/Drawer.tsx
  frontend/src/contexts/DrawerProvider.tsx
Labels: FE, REFACTOR ♻️

#224 [Feature] - user 컨텍스트에 access token만 담도록 수정 & 로그인/로그아웃 버튼 수정
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/pages/login/KakaoCallbackPage.tsx
  frontend/src/constants/endpoint.ts
  frontend/src/constants/queryKey.ts
  frontend/src/contexts/UserProvider.tsx
  frontend/src/queries/useUserProfile.ts
  frontend/src/types/domain/user.ts
Labels: FE

#225 [Feature] - 여행 계획 등록 기능 변경 & 테스트 추가
  frontend/__tests__/travelPlanRegisterPage.test.tsx
  frontend/__tests__/utils/createTravelPlanRegisterHook.tsx
  frontend/package.json
  frontend/src/components/common/Calendar/Calendar.stories.tsx
  frontend/src/components/common/Calendar/Calendar.styled.ts
  frontend/src/components/common/Calendar/Calendar.tsx
  frontend/src/components/common/Calendar/Calendar.type.ts
  frontend/src/components/common/DateRangePicker/DateRangePicker.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanDayAccordion/TravelPlanDayAccordion.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueDayAccordion/TravelogueDayAccordion.tsx
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelogueDays.ts
  frontend/src/hooks/useCalendar.ts
  frontend/src/hooks/useClickAway.ts
  frontend/src/main.tsx
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/travelPlanRegisterHandler.ts
  frontend/src/types/domain/travelPlan.ts
  frontend/src/types/domain/travelTransform.ts
  frontend/src/types/domain/travelogue.ts
  frontend/yarn.lock
Labels: FE, TEST 🧪, REFACTOR ♻️

#226 [Feature] - 여행 공유하기 기능 구현
  frontend/.prettierrc.json
  frontend/src/assets/svg/check-circle.svg
  frontend/src/assets/svg/error-circle.svg
  frontend/src/assets/svg/more.svg
  frontend/src/assets/svg/share.svg
  frontend/src/components/common/Icon/svg-icons.json
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.styled.ts
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/Toast/Toast.type.ts
  frontend/src/components/common/Toast/ToastContainer.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/pages/travelPlanDetail/ShareModal/ShareModal.style.ts
  frontend/src/components/pages/travelPlanDetail/ShareModal/ShareModal.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/constants/endpoint.ts
  frontend/src/constants/environment.ts
  frontend/src/constants/route.ts
  frontend/src/constants/uuid.ts
  frontend/src/contexts/ToastProvider/ToastProvider.constant.ts
  frontend/src/contexts/ToastProvider/ToastProvider.tsx
  frontend/src/main.tsx
  frontend/src/mocks/broswer.ts
  frontend/src/mocks/data/travelPlan.json
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/travelPlanHandler.ts
  frontend/src/mocks/handlers/travelogueInfiniteHandler.ts
  frontend/src/queries/useGetTravelPlan.ts
  frontend/src/queries/useGetTravelogue.ts
  frontend/src/queries/usePostTravelPlan.ts
  frontend/src/styles/tokens/colors.ts
  frontend/src/types/domain/travelPlan.ts
  frontend/src/utils/clipboard.ts
  frontend/src/utils/extractId.ts
  frontend/src/utils/uuid.ts
  frontend/src/utils/worker.ts
Labels: FE

#229 [Feature] - 여행 계획 & 여행기 삭제 기능 구현
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/common/Dropdown/Dropdown.styled.ts
  frontend/src/components/common/Dropdown/Dropdown.tsx
  frontend/src/components/common/Dropdown/Dropdown.type.ts
  frontend/src/components/common/index.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDeleteModal/TravelPlanDeleteModal.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDeleteModal/TravelPlanDeleteModal.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDeleteModal/TravelogueDeleteModal.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDeleteModal/TravelogueDeleteModal.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/queries/useDeleteTravelPlan.ts
  frontend/src/queries/useDeleteTravelogue.ts
Labels: FE

#235 [Feature] - 삭제 API 구현
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueDay.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePhoto.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueDayRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePlaceRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueDayService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanDay.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanDayRepository.java
  backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanPlaceRepository.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#234 [Feature] - 자체 회원 가입과 로그인 구현
  backend/build.gradle
  backend/src/main/java/kr/touroot/authentication/controller/LoginController.java
  backend/src/main/java/kr/touroot/authentication/dto/request/LoginRequest.java
  backend/src/main/java/kr/touroot/authentication/dto/response/OauthUserInformationResponse.java
  backend/src/main/java/kr/touroot/authentication/infrastructure/PasswordEncryptor.java
  backend/src/main/java/kr/touroot/authentication/service/LoginService.java
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/main/java/kr/touroot/member/controller/MemberController.java
  backend/src/main/java/kr/touroot/member/domain/LoginType.java
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/member/dto/request/MemberRequest.java
  backend/src/main/java/kr/touroot/member/repository/MemberRepository.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePhotoRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/test/java/kr/touroot/authentication/fixture/MemberFixture.java
  backend/src/test/java/kr/touroot/authentication/service/LoginServiceTest.java
  backend/src/test/java/kr/touroot/image/infrastructure/AwsS3ProviderTest.java
  backend/src/test/java/kr/touroot/member/controller/MemberControllerTest.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/member/domain/MemberTest.java
  backend/src/test/java/kr/touroot/member/fixture/MemberRequestFixture.java
  backend/src/test/java/kr/touroot/member/helper/MemberTestHelper.java
  backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java
  backend/src/test/java/kr/touroot/place/fixture/PlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueDayTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueDayFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePhotoFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanDayFixture.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanFixture.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
Labels: BE

#248 [Fix] - 삭제 API CORS 문제 해결
  backend/src/main/java/kr/touroot/global/config/WebConfig.java
Labels: BE

#243 [Fix] - JwtAuthFilter Authorization Header 파싱 오류 수정
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
Labels: BE

#238 [Feature] - 태그 생성 및 조회 API 작성
  backend/build.gradle
  backend/src/main/java/kr/touroot/TourootApplication.java
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/tag/TagController.java
  backend/src/main/java/kr/touroot/tag/cache/CacheConfig.java
  backend/src/main/java/kr/touroot/tag/domain/Tag.java
  backend/src/main/java/kr/touroot/tag/dto/TagCreateRequest.java
  backend/src/main/java/kr/touroot/tag/dto/TagResponse.java
  backend/src/main/java/kr/touroot/tag/repository/TagRepository.java
  backend/src/main/java/kr/touroot/tag/service/TagService.java
  backend/src/test/java/kr/touroot/tag/TagControllerTest.java
  backend/src/test/java/kr/touroot/tag/fixture/TagFixture.java
  backend/src/test/java/kr/touroot/tag/helper/TagTestHelper.java
  backend/src/test/java/kr/touroot/tag/service/TagServiceTest.java
Labels: BE

#244 [Feature] - 여행 계획, 여행기 하위 도메인 조회 명세 변경
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TraveloguePositionResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanDayResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanPlaceResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/TravelPlanPositionResponse.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#246 [Feature] - 이미지 업로드 용량 증가
  backend/src/main/resources/application.yml
Labels: BE

#252 [Refactor] - 메인 페이지 여행기 목록 응답에 사용자 프로필 사진 URL 추가
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java
  backend/src/test/java/kr/touroot/authentication/fixture/MemberFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
Labels: BE, REFACTOR ♻️

#257 [Feature] - 여행기 조회 응답에 작성자 정보 추가
  backend/src/main/java/kr/touroot/authentication/dto/response/LoginResponse.java
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueSimpleResponse.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
Labels: BE

#255 [Fix] - 3차 스프린트 QA 반영(리버)
  frontend/src/components/common/Calendar/Calendar.styled.ts
  frontend/src/components/common/Carousel/Carousel.styled.ts
  frontend/src/components/common/Drawer/Drawer.styled.ts
  frontend/src/components/common/FloatingButton/FloatingButton.styled.ts
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.styled.ts
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Modal/Modal.style.ts
  frontend/src/components/common/ModalBottomSheet/BackDrop/BackDrop.styled.ts
  frontend/src/components/common/ModalBottomSheet/Container/Container.styled.ts
  frontend/src/components/common/Spinner/Spinner.stories.tsx
  frontend/src/components/common/Spinner/Spinner.styled.ts
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/common/Tab/Tab.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.styled.ts
  frontend/src/components/common/Toast/Toast.styled.ts
  frontend/src/components/pages/login/Fallback/LoginFallback.stories.ts
  frontend/src/components/pages/login/Fallback/LoginFallback.styled.ts
  frontend/src/components/pages/login/Fallback/LoginFallback.tsx
  frontend/src/components/pages/login/KakaoCallbackPage.tsx
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.stories.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/constants/storage.ts
  frontend/src/queries/useDeleteTravelPlan.ts
  frontend/src/queries/useDeleteTravelogue.ts
  frontend/src/queries/usePostTravelogue.ts
  frontend/src/styles/theme.ts
  frontend/src/styles/tokens/index.ts
  frontend/src/styles/tokens/zIndex.ts
  frontend/src/types/index.ts
  frontend/src/types/style/emotion.d.ts
  frontend/src/utils/getDateRange.ts
Labels: FE

#261 [Feature] - sentry 초기 설정 변경 & 소스맵 설정 추가
  frontend/package.json
  frontend/src/main.tsx
  frontend/webpack.common.js
  frontend/yarn.lock
Labels: FE, INFRA ⚙️

#262 [Fix] - 3차 스프린트 QA 반영(시모)
  frontend/src/components/common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/common/Dropdown/Dropdown.tsx
  frontend/src/components/common/FloatingButton/FloatingButton.styled.ts
  frontend/src/components/common/FloatingButton/FloatingButton.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/pages/login/KakaoCallbackPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/queries/useDeleteTravelPlan.ts
  frontend/src/queries/useDeleteTravelogue.ts
  frontend/src/queries/usePostTravelPlan.ts
  frontend/src/queries/usePostTravelogue.ts
  frontend/src/types/domain/travelogue.ts
  frontend/src/types/domain/user.ts
Labels: FE

#263 [Feature] - 배포한 서비스를 모니터링 하는 도구 GA 세팅
  frontend/package.json
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/main.tsx
  frontend/yarn.lock
Labels: FE

#264 [Feature] - 예외 로깅 시 InternalServerError 는 스택 트레이스도 같이 로깅하도록 변경
  backend/src/main/java/kr/touroot/authentication/dto/response/LoginResponse.java
  backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/kr/touroot/member/dto/request/MemberRequest.java
Labels: BE

#270 [Fix] - 장소 설명이 255자를 넘어가는 여행기, 여행 계획이 저장 되지 않는 오류 수정
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
Labels: BE

#271 [Fix] - 이미지 최대 업로드 개수 검증 누락 해결
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE

#266 [Fix] - 한 Day 내 중복된 장소 이름이 존재할 경우 게시물이 지속적으로 생기는 문제 해결
  frontend/src/components/common/Calendar/Calendar.tsx
  frontend/src/components/common/Carousel/Carousel.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
Labels: FE

#278 [Fix] - InternalServerError 로깅 시 예외 스택 트레이스가 제대로 로깅되지 않는 문제 해결
  backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
Labels: BE

#276 [Fix] - 3차 스프린트 QA 반영 2차 (리버)
  frontend/src/components/common/AvatarCircle/AvatarCircle.styled.ts
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
Labels: FE

#275 [Fix] - 3차 스프린트 QA 반영 2차 (시모)
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/queries/useDeleteTravelPlan.ts
  frontend/src/queries/useDeleteTravelogue.ts
  frontend/src/queries/useGetTravelogue.ts
Labels: FE

#280 [Fix] - 3차 스프린트 QA 반영 2차 (지니)
  frontend/public/index.html
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Calendar/Calendar.tsx
  frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx
  frontend/src/constants/errorMessage.ts
Labels: FE

#283 refactor: 마커 색상 변경 & 여행기 상세 페이지 title & subtitle 순서 변경
  frontend/src/components/common/GoogleMapView/GoogleMapView.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
Labels: FE, REFACTOR ♻️

#284 [Fix] - S3 이미지 오류 예외 메시지 변경
  backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/kr/touroot/global/exception/S3UploadException.java
  backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/test/java/kr/touroot/image/infrastructure/AwsS3ProviderTest.java
Labels: BE

#286 [Feature] - 외부 API request/response 로깅
  backend/src/main/java/kr/touroot/authentication/infrastructure/KakaoOauthClient.java
Labels: BE

#289 [Fix] - 여행 날짜가 하나도 추가되지 않은 여행기가 정상 작성되버리는 문제 발생
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueDayRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
Labels: BE

#291 [Fix] - 코드 오타 및 적절하지 않은 객체 타입 수정
  backend/src/main/java/kr/touroot/member/repository/MemberRepository.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
Labels: BE

#293 [Feature] - refresh token 개발
  backend/src/main/java/kr/touroot/authentication/controller/LoginController.java
  backend/src/main/java/kr/touroot/authentication/dto/request/TokenReissueRequest.java
  backend/src/main/java/kr/touroot/authentication/dto/response/LoginResponse.java
  backend/src/main/java/kr/touroot/authentication/dto/response/TokenResponse.java
  backend/src/main/java/kr/touroot/authentication/infrastructure/JwtTokenProvider.java
  backend/src/main/java/kr/touroot/authentication/service/LoginService.java
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application.yml
  backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java
  backend/src/test/java/kr/touroot/authentication/helper/LoginTestHelper.java
  backend/src/test/java/kr/touroot/authentication/infrastructure/JwtTokenProviderTest.java
  backend/src/test/java/kr/touroot/authentication/service/LoginServiceTest.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/resources/application-test.yml
Labels: BE

#292 [Fix] - 만료된 access token 핸들링
  frontend/src/apis/interceptor.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
Labels: FE

#295 [Fix] - 삭제 및 등록 시 여러번 요청하지 못하게 수정
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/hooks/useLeadingDebounce.ts
Labels: FE

#305 [Feature] - 여행기 작성/조회 시 태그 추가
  backend/src/main/java/kr/touroot/tag/controller/TagController.java
  backend/src/main/java/kr/touroot/tag/dto/TagResponse.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueTag.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueSimpleResponse.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueTagRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java
  backend/src/test/java/kr/touroot/tag/fixture/TagFixture.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
Labels: BE

#311 [Feature] - 사용자 닉네임 수정 기능 구현
  backend/src/main/java/kr/touroot/global/config/WebConfig.java
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/member/dto/request/ProfileUpdateRequest.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/member/domain/MemberTest.java
  backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java
Labels: BE

#302 [Feature] - 여행기 제목 기준 검색 기능 구현
  backend/build.gradle
  backend/src/main/java/kr/touroot/global/config/QueryDslConfig.java
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueSearchRequest.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/kr/touroot/global/config/TestQueryDslConfig.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE

#307 [Feature] - refresh token 클라이언트 내 적용
  frontend/src/apis/client.ts
  frontend/src/apis/interceptor.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/pages/login/KakaoCallbackPage.tsx
  frontend/src/constants/endpoint.ts
  frontend/src/types/domain/user.ts
Labels: FE

#314 [Feature] - TravelogueCard 컴포넌트 리팩터링
  frontend/src/components/common/Icon/svg-icons.json
  frontend/src/components/pages/main/MainPage.styled.ts
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.stories.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.styled.ts
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/mocks/data/travelogue.json
  frontend/src/types/domain/travelogue.ts
  frontend/src/types/index.ts
Labels: FE, REFACTOR ♻️

#310 [Feature] - Input 컴포넌트 리팩토링
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Input/Input.type.ts
Labels: FE

#296 Fix - image error 처리 누락, 여행기 삭제시 마이페이지로 넘어갈 때 tab 초기값 수정 , 여행기 썸네일
  frontend/src/components/common/Tab/Tab.tsx
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/components/pages/travelogueDetail/Thumbnail/Thumbnail.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.stories.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.tsx
  frontend/src/constants/storage.ts
  frontend/src/queries/useDeleteTravelogue.ts
Labels: FE

#319 [Feature] - 여행 계획 TODO 기능을 구현
  backend/src/main/java/kr/touroot/authentication/service/LoginService.java
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/main/java/kr/touroot/travelplan/controller/PlaceTodoController.java
  backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlaceTodo.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanCreateRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceCreateRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceTodoRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/TodoStatusUpdateRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanCreateResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanDayResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPlaceResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPlaceTodoResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPositionResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanResponse.java
  backend/src/main/java/kr/touroot/travelplan/repository/PlaceTodoQueryRepository.java
  backend/src/main/java/kr/touroot/travelplan/repository/PlaceTodoQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelplan/repository/PlaceTodoRepository.java
  backend/src/main/java/kr/touroot/travelplan/service/PlaceTodoService.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/kr/touroot/authentication/fixture/MemberFixture.java
  backend/src/test/java/kr/touroot/authentication/helper/LoginTestHelper.java
  backend/src/test/java/kr/touroot/authentication/service/LoginServiceTest.java
  backend/src/test/java/kr/touroot/global/config/TestQueryDslConfig.java
  backend/src/test/java/kr/touroot/member/fixture/MemberFixture.java
  backend/src/test/java/kr/touroot/member/helper/MemberTestHelper.java
  backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/controller/PlaceTodoControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlaceTodoTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanFixture.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanPlaceFixture.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/service/PlaceTodoServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#321 [Feature] - 여행기 수정 기능 구현
  backend/src/main/java/kr/touroot/global/entity/BaseEntity.java
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueDayRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePlaceRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueTagRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueDayService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE

#327 [Fix] - Icon, Icon Button storybook에서 iconType option 적용되도록 수정
  frontend/src/components/common/Icon/Icon.stories.tsx
  frontend/src/components/common/IconButton/IconButton.stories.tsx
Labels: FE, TEST 🧪

#333 [Feature] - 여행 계획 TO DO 기능 구현
  frontend/__tests__/travelPlanRegisterPage.test.tsx
  frontend/src/assets/svg/check.svg
  frontend/src/components/common/Calendar/Calendar.stories.tsx
  frontend/src/components/common/Calendar/Calendar.tsx
  frontend/src/components/common/Checkbox/Checkbox.stories.tsx
  frontend/src/components/common/Checkbox/Checkbox.styled.ts
  frontend/src/components/common/Checkbox/Checkbox.tsx
  frontend/src/components/common/Icon/svg-icons.json
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/pages/travelPlanDetail/ShareModal/ShareModal.style.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanTodoItem/TravelPlanTodoItem.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanTodoItem/TravelPlanTodoItem.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.stories.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.styled.ts
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanDayAccordion/TravelPlanDayAccordion.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.styled.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/endpoint.ts
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/mocks/data/travelPlan.json
  frontend/src/mocks/handlers/travelPlanHandler.ts
  frontend/src/mocks/handlers/travelPlanSharedDetailHandler.ts
  frontend/src/mocks/handlers/travelPlanTodoPatchHandler.ts
  frontend/src/queries/usePatchTravelPlanTodo.ts
  frontend/src/types/domain/travelPlan.ts
Labels: FE

#336 [Feature] - 좋아요 기능 구현
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueLike.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueLikeResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueSimpleResponse.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueLikeServiceTest.java
Labels: BE

#335 [Feature] - tag 기능 구현
  frontend/__tests__/utils/createInfiniteTravelogueHook.tsx
  frontend/src/components/common/Chip/Chip.stories.tsx
  frontend/src/components/common/Chip/Chip.styled.ts
  frontend/src/components/common/Chip/Chip.tsx
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.tsx
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/common/Tab/Tab.tsx
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/common/Text/Text.type.ts
  frontend/src/components/common/index.ts
  frontend/src/components/pages/main/MainPage.styled.ts
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.stories.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.styled.ts
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.styled.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/endpoint.ts
  frontend/src/constants/formValidation.ts
  frontend/src/constants/queryKey.ts
  frontend/src/hooks/useDragScroll.ts
  frontend/src/hooks/useTagSelection.ts
  frontend/src/mocks/data/travelogue.json
  frontend/src/mocks/handlers/travelogueInfiniteHandler.ts
  frontend/src/queries/useGetTags.ts
  frontend/src/queries/useInfiniteTravelogues.ts
  frontend/src/types/domain/travelogue.ts
Labels: FE

#322 [Feature] - Local 환경에서는 임베디드 S3를 사용하도록 적용
  backend/build.gradle
  backend/src/main/java/kr/touroot/global/config/AwsS3Config.java
  backend/src/main/java/kr/touroot/global/config/EmbeddedS3Config.java
  backend/src/main/java/kr/touroot/image/controller/ImageController.java
  backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/test/java/kr/touroot/image/infrastructure/AwsS3ProviderTest.java
Labels: BE

#332 [Feature] - 여행기 장소 이미지 업로드 중일 경우, spinner를 보여주도록 리팩터링
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.stories.tsx
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.styled.ts
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.tsx
  frontend/src/components/common/Spinner/Spinner.stories.tsx
  frontend/src/components/common/Spinner/Spinner.styled.ts
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/components/common/Spinner/Spinner.type.ts
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.constants.ts
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
Labels: FE, REFACTOR ♻️

#317 [Feature] - 사용자 닉네임 수정
  frontend/src/components/pages/my/MyPage.styled.ts
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/modifyMemberNicknameHandler.ts
  frontend/src/queries/usePatchNickname.ts
Labels: FE

#344 [Fix] bean 중복 오류 수정
  backend/src/main/java/kr/touroot/global/config/EmbeddedS3Config.java
Labels: BE

#328 [Feature] - 검색 구현
  frontend/.storybook/preview.tsx
  frontend/src/assets/svg/home-icon.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/search-icon.svg
  frontend/src/components/common/Header/DefaultHeader/DefaultHeader.tsx
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Header/HomePageHeader/HomePageHeader.tsx
  frontend/src/components/common/Header/SearchHeader/SearchHeader.styled.ts
  frontend/src/components/common/Header/SearchHeader/SearchHeader.tsx
  frontend/src/components/common/Header/SearchResultPageHeaderHeader/SearchResultPageHeader.tsx
  frontend/src/components/common/Header/index.ts
  frontend/src/components/common/Icon/svg-icons.json
  frontend/src/components/common/index.ts
  frontend/src/components/layout/AppLayout/AppLayout.tsx
  frontend/src/components/pages/search/SearchPage.styled.ts
  frontend/src/components/pages/search/SearchPage.tsx
  frontend/src/components/pages/search/fallback/SearchFallback.styled.ts
  frontend/src/components/pages/search/fallback/SearchFallback.tsx
  frontend/src/constants/endpoint.ts
  frontend/src/constants/queryKey.ts
  frontend/src/constants/route.ts
  frontend/src/queries/useInfiniteSearchTravelogues.ts
  frontend/src/router.tsx
Labels: FE

#334 [Feature] - 여행기 상세보기 페이지에서 지도 상세보기 구현
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/map-icon.svg
  frontend/src/components/common/Box/Box.styled.ts
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Icon/svg-icons.json
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
Labels: FE

#341 [Feature] - 여행 계획 수정 기능 구현
  backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanDayRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceTodoRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPositionRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanRequest.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#347 [Fix] - 삭제 기능 쿼리 문제 해결
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java
Labels: BE

#342 [Feature] - 여행기 좋아요 기능 구현
  frontend/src/assets/svg/empty-heart.svg
  frontend/src/assets/svg/heart.svg
  frontend/src/components/common/Icon/svg-icons.json
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/constants/endpoint.ts
  frontend/src/mocks/handlers/activeTravelogueHeartHandler.ts
  frontend/src/mocks/handlers/inactiveTravelogueHeartHandler.ts
  frontend/src/mocks/handlers/travelogueDetailHandler.ts
  frontend/src/mocks/handlers/travelogueInfiniteHandler.ts
  frontend/src/queries/useDeleteUpdateHeart.ts
  frontend/src/queries/useGetTravelogue.ts
  frontend/src/queries/usePostUpdateHeart.ts
  frontend/src/styles/tokens/colors.ts
Labels: FE

#345 [Feature] - Spring boot Prod 프로필 분리
  backend/Dockerfile
  backend/src/main/java/kr/touroot/global/config/SwaggerConfig.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: BE

#352 [Fix] - JPQL 관련 alias ambiguous 예외 발생
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePlaceRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueTagRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueDayQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueDayQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePhotoQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePhotoQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePlaceQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePlaceQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueTagQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueTagQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueDayService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java
  backend/src/test/java/kr/touroot/global/config/TestQueryDslConfig.java
  backend/src/test/java/kr/touroot/tag/service/TagServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
Labels: BE

#355 [Fix] - JPQL 관련 alias ambiguous 예외 발생
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueDayRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePlaceRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueDayQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueDayQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePhotoQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePhotoQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePlaceQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TraveloguePlaceQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueDayService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/test/java/kr/touroot/global/config/TestQueryDslConfig.java
Labels: BE

#358 [Feature] - Production 서버 CI/CD 파이프라인 구축
  .github/workflows/be-cd-prod.yml
Labels: BE, INFRA ⚙️

#366 [Fix] - 여행기 수정 시 이미 업로드 된 사진을 처리하지 못하는 오류
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
Labels: BE

#365 [Fix] - Prod CORS 허용 및 태그 필터링 정렬 순서 변경
  backend/src/main/java/kr/touroot/global/config/WebConfig.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application-test.yml
Labels: BE

#360 [Feature] - 엔티티 필수값 명세 재정의
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
Labels: BE

#373 [Fix] - S3 image base url Profile 별로 분리
  backend/src/main/java/kr/touroot/global/config/AwsS3Config.java
  backend/src/main/resources/application.yml
Labels: BE

#368 [Feature] - 플로팅 버튼에 여행 계획 작성 추가
  frontend/src/components/common/FloatingButton/FloatingButton.styled.ts
  frontend/src/components/common/FloatingButton/FloatingButton.tsx
  frontend/src/styles/tokens/zIndex.ts
Labels: FE

#361 [Feature] - required 구현
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/TextField/TextField.stories.tsx
  frontend/src/components/common/TextField/TextField.styled.ts
  frontend/src/components/common/TextField/TextField.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.stories.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/styles/tokens/colors.ts
Labels: FE, REFACTOR ♻️

#374 [Fix] - 4차 스프린트 QA 반영 1차 (시모)
  frontend/__tests__/travelPlanRegisterPage.test.tsx
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.styled.ts
  frontend/src/components/common/TransformBottomSheet/TransformBottomSheet.tsx
  frontend/src/components/pages/main/MainPage.styled.ts
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/my/MyTravelPlans/MyTravelPlans.styled.ts
  frontend/src/components/pages/my/MyTravelPlans/MyTravelPlans.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelogueDays.ts
  frontend/src/queries/useInfiniteTravelogues.ts
Labels: FE, REFACTOR ♻️

#375 [Fix] - 4차 스프린트 QA 반영 1차 (지니)
  frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/components/pages/travelPlanDetail/ShareModal/ShareModal.style.ts
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
  frontend/src/queries/useDeleteUpdateHeart.ts
  frontend/src/queries/usePatchNickname.ts
  frontend/src/queries/usePostUpdateHeart.ts
Labels: FE

#378 [Feature] - 프론트엔드 dev, prod 분리 작업
  .github/workflows/frontend-ci-development.yml
  .github/workflows/frontend-ci.production.yml
  frontend/.gitignore
  frontend/.storybook/main.ts
  frontend/babel.config.json
  frontend/package.json
  frontend/webpack.common.js
  frontend/webpack.development.js
  frontend/webpack.production.js
  frontend/yarn.lock
Labels: FE

#376 [Fix] - 4차 스프린트 QA 반영 1차 (리버)
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Header/SearchHeader/SearchHeader.tsx
  frontend/src/components/common/TextField/TextField.styled.ts
  frontend/src/components/common/TextField/TextField.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.stories.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.styled.ts
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.stories.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/PlaceDetailCard/PlaceDetailCard.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/queries/useInfiniteSearchTravelogues.ts
Labels: FE

#382 [Feature] - prod profile CORS allowedOrigins에 www 서브 도메인 추가
  backend/src/main/resources/application.yml
Labels: BE

#380 [Feature] - 404 NotFound 페이지 구현
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.tsx
  frontend/src/components/pages/notFound/NotFoundPage.styled.ts
  frontend/src/components/pages/notFound/NotFoundPage.tsx
  frontend/src/router.tsx
Labels: FE

#384 [Fix] - 여행기 삭제시 TravelogueTag 도 삭제하도록 변경
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java
Labels: BE

#388 [Feature] - 투룻 프로덕션 배포
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java
  backend/src/main/resources/application.yml
Labels: BE

#392 [Fix] - 여행기 썸네일이 유저로부터 입력되지 않은 경우 기본 이미지를 사용하지 못하는 오류 해결
  backend/src/main/java/kr/touroot/image/infrastructure/AwsS3Provider.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
Labels: BE

#391 [Fix] - 로딩, 에러 처리 및 메인페이지, 로그인 콜백 페이지 오류 수정
  frontend/.gitignore
  frontend/src/components/pages/login/Fallback/LoginFallback.styled.ts
  frontend/src/components/pages/login/Fallback/LoginFallback.tsx
  frontend/src/components/pages/login/KakaoCallbackPage.tsx
  frontend/src/components/pages/login/LoginPage.styled.ts
  frontend/src/components/pages/login/LoginPage.tsx
  frontend/src/components/pages/main/MainPage.styled.ts
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDeleteModal/TravelogueDeleteModal.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDeleteModal/TravelogueDeleteModal.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/hooks/pages/useTravelogueDays.ts
  frontend/src/queries/usePostKakaoLogin.ts
Labels: FE

#393 [Fix] - 여행 계획 수정, 마이페이지, 검색 페이지 에러 핸들링
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/components/pages/my/MyTravelPlans/MyTravelPlans.tsx
  frontend/src/components/pages/my/MyTravelogues/MyTravelogues.tsx
  frontend/src/components/pages/search/SearchPage.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/main.tsx
  frontend/src/queries/useInfiniteMyTravelPlans.ts
  frontend/src/queries/useInfiniteMyTravelogues.ts
  frontend/src/queries/useInfiniteSearchTravelogues.ts
Labels: FE

#394 [Fix] - 여행기 등록 & 수정, 여행 계획 등록, 여행 계획 상세 페이지 예외 및 로딩 처리
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueDayAccordion/TravelogueDayAccordion.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/queries/useDeleteTravelPlan.ts
  frontend/src/queries/usePostTravelPlan.ts
  frontend/src/queries/usePostTravelogue.ts
  frontend/src/queries/usePostUploadImages.ts
Labels: FE

#400 [Fix] - 4차 스프린트 QA 반영 2차 (시모)
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Button/Button.type.ts
  frontend/src/components/common/FloatingButton/FloatingButton.styled.ts
  frontend/src/components/common/FloatingButton/FloatingButton.tsx
  frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.stories.tsx
  frontend/src/components/common/ModalBottomSheet/ModalBottomSheet.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDeleteModal/TravelPlanDeleteModal.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDeleteModal/TravelPlanDeleteModal.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDeleteModal/TravelogueDeleteModal.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDeleteModal/TravelogueDeleteModal.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/debouncedTime.ts
  frontend/src/hooks/pages/useTravelPlanDays.ts
Labels: FE

#401 [Fix] - 4차 스프린트 QA 반영 2차 (리버)
  frontend/src/components/common/Box/Box.styled.ts
  frontend/src/components/common/Box/Box.tsx
  frontend/src/components/common/Header/SearchHeader/SearchHeader.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.stories.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.styled.ts
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.tsx
  frontend/src/components/pages/main/TravelogueCard/TravelogueCard.tsx
  frontend/src/components/pages/search/SearchPage.styled.ts
  frontend/src/components/pages/search/SearchPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/queries/useInfiniteSearchTravelogues.ts
Labels: FE

#404 [Fix] - 여행 계획 상세 페이지 내 작성자 아닌 게시물 접근 시 alert가 2번 뜨는 현상 개선
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
Labels: FE

#407 [Fix] - line height,shareModal 수정
  frontend/src/components/pages/travelPlanDetail/ShareModal/ShareModal.style.ts
  frontend/src/components/pages/travelPlanDetail/ShareModal/ShareModal.tsx
  frontend/src/styles/tokens/typography.ts
Labels: FE
