Repository woowacourse-teams/2024-touroot, pull requests merged in 2024-10, with the labels that each got.

#493 [Fix] - 여행기 수정 시 썸네일을 임시 저장소에만 저장하는 버그 수정
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
Labels: BE

#498 [Feature] - health checker api 로깅 필터 안거치게 변경
  backend/src/main/java/kr/touroot/global/auth/JwtAuthFilter.java
  backend/src/main/java/kr/touroot/global/logging/LoggingFilter.java
Labels: BE

#503 [Feature] - CORS 설정에서 exposeHeader 추가
  backend/src/main/java/kr/touroot/global/config/WebConfig.java
Labels: BE

#501 [Refactor] - API 요청 및 응답 명세 통일
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
  backend/src/main/java/kr/touroot/member/dto/MyTravelPlanResponse.java
  backend/src/main/java/kr/touroot/member/dto/response/MyTravelogueResponse.java
  backend/src/main/java/kr/touroot/member/dto/response/ProfileResponse.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueCreateResponse.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelplan/controller/PlaceTodoController.java
  backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/TodoStatusUpdateRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPlaceTodoResponse.java
  backend/src/main/java/kr/touroot/travelplan/service/PlaceTodoService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/controller/PlaceTodoControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/service/PlaceTodoServiceTest.java
Labels: BE

#508 [Refactor] - API 요청 및 응답 명세 통일
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanTodoItem/TravelPlanTodoItem.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/mocks/data/travelPlan.json
  frontend/src/queries/usePatchTravelPlanTodo.ts
  frontend/src/queries/usePostTravelPlan.ts
  frontend/src/queries/usePutTravelPlan.ts
  frontend/src/types/domain/travelPlan.ts
Labels: FE, REFACTOR ♻️

#495 [Feature] - Immer을 사용한 코드 구조 개선
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/hooks/pages/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelPlanForm.ts
  frontend/src/hooks/pages/useTravelogueDays.ts
  frontend/src/queries/usePostTravelogue.ts
  frontend/src/queries/usePutTravelogue.ts
  frontend/src/types/domain/travelTransform.ts
  frontend/src/types/domain/travelogue.ts
  frontend/src/utils/getDaysAndNights.ts
  frontend/src/utils/getInitialTravelTitle.ts
  frontend/src/utils/queryFunction.ts
Labels: FE, REFACTOR ♻️

#497 [Feature] - prod 프로필 SSL 인증서 제거
  .github/workflows/be-cd-prod.yml
  backend/src/main/resources/application.yml
Labels: BE

#507 [Refactor] - 여행 계획 Service 코드 리팩터링
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/main/java/kr/touroot/travelplan/controller/TravelPlanController.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlaceTodo.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlan.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanDay.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanDayRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanCreateResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanDayResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPlaceResponse.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanResponse.java
  backend/src/main/java/kr/touroot/travelplan/repository/PlaceTodoRepository.java
  backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanDayRepository.java
  backend/src/main/java/kr/touroot/travelplan/repository/TravelPlanPlaceRepository.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanFacadeService.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanService.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanDayTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanFixture.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE, REFACTOR ♻️

#504 [Refactor] - 여행기 Service 코드 리팩터링
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/main/java/kr/touroot/tag/dto/TagResponse.java
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueDay.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePhoto.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueDayRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePhotoRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueDayResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TraveloguePlaceResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueResponse.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TravelogueSimpleResponse.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueDayRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePhotoRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/TraveloguePlaceRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueDayService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueImagePerpetuationService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePhotoService.java
  backend/src/main/java/kr/touroot/travelogue/service/TraveloguePlaceService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueTagService.java
  backend/src/main/java/kr/touroot/travelplan/service/TravelPlanFacadeService.java
  backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueDayTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePlaceTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueDayServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueLikeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePhotoServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TraveloguePlaceServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE, REFACTOR ♻️

#522 [Feature] - 무중단 배포 반영 CI/CD 파이프라인 작성
  .github/workflows/be-cd-prod.yml
Labels: BE, INFRA ⚙️

#525 [Feature] - 프로덕션 api-v1.1.3 배포
  .github/workflows/be-cd-prod.yml
Labels: BE, REFACTOR ♻️

#488 [Fix] - 지도 장소명이 한국말이 아닌 영어로 나오는 이슈
  frontend/src/components/common/GoogleMapLoadScript/GoogleMapLoadScript.tsx
Labels: FE

#511 [Feature] - 여행 계획 & 여행기 상세 페이지로 이동 시 scroll 최상단으로 이동 되도록 변경
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
Labels: FE, REFACTOR ♻️

#520 [Feature] - 여행기 & 여행 계획 등록/수정 페이지 리팩터링
  frontend/__tests__/travelPlanRegisterPage.test.tsx
  frontend/src/components/common/MultiImageUpload/MultiImageUpload.tsx
  frontend/src/components/common/Tab/Tab.tsx
  frontend/src/components/common/TextField/TextField.stories.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.stories.tsx
  frontend/src/components/common/ThumbnailUpload/ThumbnailUpload.tsx
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanEdit/hooks/useTravelPlanEdit.ts
  frontend/src/components/pages/travelPlanEdit/hooks/useTravelPlanInitialization.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelPlanRegister/hooks/useTravelPlanRegister.ts
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueEdit/hooks/useAuthorCheck.ts
  frontend/src/components/pages/travelogueEdit/hooks/useTravelogueEdit.ts
  frontend/src/components/pages/travelogueEdit/hooks/useTravelogueInitialization.ts
  frontend/src/components/pages/travelogueRegister/TravelogueDayAccordion/TravelogueDayAccordion.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/TravelogueMultiImageUpload.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/components/pages/travelogueRegister/hooks/useTravelogueRegister.ts
  frontend/src/hooks/pages/useTravelPlanForm.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanFormState.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanStartDate.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanTitle.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueDays.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueFormState.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueThumbnail.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueTitle.ts
  frontend/src/hooks/useAuthRedirect.ts
  frontend/src/hooks/useDragScroll.ts
  frontend/src/hooks/useMultiSelectionTag.ts
  frontend/src/hooks/useToggle.ts
  frontend/src/types/domain/travelTransform.ts
Labels: FE, REFACTOR ♻️

#421 [Feature] - 사용자 프로필 이미지 수정 기능 구현
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/member/dto/request/ProfileUpdateRequest.java
  backend/src/main/java/kr/touroot/member/dto/response/ProfileResponse.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/member/domain/MemberTest.java
  backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanFacadeServiceTest.java
Labels: BE

#547 [Fix] - flyway 스크립트 파일 네이밍 규칙이 맞지 않아 실행되지 않는 버그 수정
  backend/src/main/resources/db/migration/mysql/V6__add_travelogue_country.sql
Labels: BE

#549 [Fix] - 스키마와 엔티티 사이의 컬럼 타입 불일치로 인한 버그 해결
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueCountry.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueCountryService.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueCountryFixture.java
Labels: BE

#540 [Feature] - 자신이 좋아요를 누른 게시글을 조회하는 기능 구현
  backend/src/main/java/kr/touroot/member/controller/MyPageController.java
  backend/src/main/java/kr/touroot/member/dto/response/MyLikeTravelogueResponse.java
  backend/src/main/java/kr/touroot/member/service/MyPageFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueLikeServiceTest.java
Labels: BE

#542 [Fix] 프로필 사진 빈 값 예외처리 삭제
  backend/src/main/java/kr/touroot/member/domain/Member.java
  backend/src/main/java/kr/touroot/member/dto/request/ProfileUpdateRequest.java
  backend/src/main/java/kr/touroot/member/service/MemberService.java
Labels: BE

#535 [Feature] - 프로필 이미지 수정 기능 및 여행기 등록 시 여행 장소마다 국가 코드 주도록 구현
  frontend/__tests__/travelPlanRegisterPage.test.tsx
  frontend/src/components/common/AvatarCircle/AvatarCircle.stories.tsx
  frontend/src/components/common/AvatarCircle/AvatarCircle.tsx
  frontend/src/components/common/Drawer/Drawer.styled.ts
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/Header/SearchHeader/SearchHeader.tsx
  frontend/src/components/pages/main/MainPage.styled.ts
  frontend/src/components/pages/my/MyPage.styled.ts
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/components/pages/my/MyTravelogues/MyTravelogues.tsx
  frontend/src/components/pages/my/ProfileImageEditModalBottomSheet/ProfileImageEditModalBottomSheet.styled.ts
  frontend/src/components/pages/my/ProfileImageEditModalBottomSheet/ProfileImageEditModalBottomSheet.tsx
  frontend/src/components/pages/my/constants.ts
  frontend/src/components/pages/my/hooks/useMyPage.ts
  frontend/src/components/pages/my/hooks/useProfileEdit.ts
  frontend/src/components/pages/my/hooks/useProfileImage.ts
  frontend/src/components/pages/my/hooks/useProfileInitialization.ts
  frontend/src/components/pages/my/hooks/useProfileNickname.ts
  frontend/src/components/pages/search/SearchPage.tsx
  frontend/src/components/pages/search/constants.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanDayAccordion/TravelPlanDayAccordion.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueDayAccordion/TravelogueDayAccordion.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueDays.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueThumbnail.ts
  frontend/src/queries/useInfiniteSearchTravelogues.ts
  frontend/src/queries/usePostUploadImages.ts
  frontend/src/queries/usePutProfile.ts
  frontend/src/types/domain/common.ts
  frontend/src/types/domain/travelPlan.ts
  frontend/src/types/domain/travelogue.ts
Labels: FE

#545 [Fix] - 6차 피드백 반영(시모)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/reset-icon.svg
  frontend/src/assets/svg/sort-icon.svg
  frontend/src/components/common/Chip/Chip.tsx
  frontend/src/components/common/Icon/svg-icons.json
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueFormState.ts
  frontend/src/hooks/useMultiSelectionTag.ts
  frontend/src/hooks/useSingleSelectionTag.ts
  frontend/yarn.lock
Labels: FE, REFACTOR ♻️

#555 [Feature] - 검색 쿼리 분기 계층 변경
  backend/src/main/java/kr/touroot/travelogue/domain/search/CountryCode.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/kr/touroot/travelogue/domain/search/CountryCodeTest.java
Labels: BE

#557 [Feature] - 검색 + 필터링 API 통합
  backend/src/main/java/kr/touroot/travelogue/controller/TravelogueController.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/SearchCondition.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TravelogueSearchRequest.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
Labels: BE

#537 [Fix] - 여행기 & 여행 계획 등록 과정에서 클라이언트 내에서 유효성 검사를 하도록 변경
  frontend/src/components/common/CharacterCount/CharacterCount.tsx
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.styled.ts
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanDayAccordion/TravelPlanDayAccordion.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.styled.ts
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.styled.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/constants/formValidation.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanDays.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanFormState.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanStartDate.ts
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanTitle.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueDays.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueFormState.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueThumbnail.ts
  frontend/src/hooks/pages/useTravelogueFormState/useTravelogueTitle.ts
  frontend/src/utils/validation/travelPlan.ts
  frontend/src/utils/validation/travelogue.ts
Labels: FE

#568 [Feature] - 여행기, 여행 계획 엔티티에 국가 코드 컬럼 추가
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/CountryCode.java
  backend/src/main/java/kr/touroot/travelogue/dto/request/TraveloguePlaceRequest.java
  backend/src/main/java/kr/touroot/travelogue/dto/response/TraveloguePlaceResponse.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/main/java/kr/touroot/travelplan/dto/request/PlanPlaceRequest.java
  backend/src/main/java/kr/touroot/travelplan/dto/response/PlanPlaceResponse.java
  backend/src/main/resources/db/migration/mysql/V6.0__add_travelogue_country.sql
  backend/src/main/resources/db/migration/mysql/V6.1__add_country_code_column.sql
  backend/src/main/resources/db/migration/mysql/V6.2__update_country_code_none.sql
  backend/src/main/resources/db/migration/mysql/V6.3__add_not_null_contraint_to_country_code.sql
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePlaceTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueResponseFixture.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanPlaceFixture.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanTestHelper.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE

#539 [Feature] - 랜딩 페이지 구현
  frontend/cypress/e2e/mainPage.cy.ts
  frontend/cypress/support/commands.ts
  frontend/src/assets/webp/bigTturi.webp
  frontend/src/assets/webp/index.ts
  frontend/src/assets/webp/mainPage.webp
  frontend/src/assets/webp/speechBubbleLeft.webp
  frontend/src/assets/webp/speechBubbleRight.webp
  frontend/src/assets/webp/travelPlanDetailPage.webp
  frontend/src/assets/webp/travelogueDetailPage.webp
  frontend/src/components/common/Header/DefaultHeader/DefaultHeader.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Header/SearchHeader/SearchHeader.tsx
  frontend/src/components/common/Text/Text.styled.ts
  frontend/src/components/common/Text/Text.tsx
  frontend/src/components/layout/AppLayout/AppLayout.tsx
  frontend/src/components/pages/landing/Animation.styled.ts
  frontend/src/components/pages/landing/FirstPage/FirstPage.styled.ts
  frontend/src/components/pages/landing/FirstPage/FirstPage.tsx
  frontend/src/components/pages/landing/FourthPage/FourthPage.styled.ts
  frontend/src/components/pages/landing/FourthPage/FourthPage.tsx
  frontend/src/components/pages/landing/FourthPage/SpeechBubble/SpeechBubble.styled.ts
  frontend/src/components/pages/landing/FourthPage/SpeechBubble/SpeechBubble.tsx
  frontend/src/components/pages/landing/LandingPage.styled.ts
  frontend/src/components/pages/landing/LandingPage.tsx
  frontend/src/components/pages/landing/SecondPage/SecondPage.styled.ts
  frontend/src/components/pages/landing/SecondPage/SecondPage.tsx
  frontend/src/components/pages/landing/ThirdPage/ThirdPage.styled.ts
  frontend/src/components/pages/landing/ThirdPage/ThirdPage.tsx
  frontend/src/components/pages/landing/ThirdPage/Title/Title.styled.ts
  frontend/src/components/pages/landing/ThirdPage/Title/Title.tsx
  frontend/src/components/pages/landing/components/Box.styled.ts
  frontend/src/components/pages/landing/components/Box.tsx
  frontend/src/components/pages/landing/hook/useAnimationObserver.ts
  frontend/src/components/pages/landing/hook/useScrollAnimation.ts
  frontend/src/components/pages/notFound/NotFoundPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/constants/route.ts
  frontend/src/hooks/usePreviousPage.ts
  frontend/src/queries/usePostKakaoLogin.ts
  frontend/src/router.tsx
Labels: FE

#566 [Feature] - 여행기 및 여행 계획 상세페이지 접근성 개선
  frontend/src/components/common/Carousel/Carousel.styled.ts
  frontend/src/components/common/Carousel/Carousel.tsx
  frontend/src/components/common/Checkbox/Checkbox.styled.ts
  frontend/src/components/common/Checkbox/Checkbox.tsx
  frontend/src/components/common/Dropdown/Dropdown.styled.ts
  frontend/src/components/common/Modal/DeleteModal/DeleteModal.tsx
  frontend/src/components/common/Tab/Tab.styled.ts
  frontend/src/components/common/Tab/Tab.tsx
  frontend/src/components/pages/my/MyPage.styled.ts
  frontend/src/components/pages/my/MyPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanDetailPage.tsx
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlansTabContent/TravelPlansTabContent.tsx
  frontend/src/components/pages/travelogueDetail/Thumbnail/Thumbnail.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueDetailPage.tsx
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.styled.ts
  frontend/src/components/pages/travelogueDetail/TravelogueTabContent/TravelogueTabContent.tsx
  frontend/src/hooks/pages/useTravelPlanFormState/useTravelPlanStartDate.ts
Labels: FE, REFACTOR ♻️

#554 [Feature] - 여행 계획 등록 페이지 접근성 개선
  frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.styled.ts
  frontend/src/components/common/Accordion/AccordionTrigger/AccordionTrigger.tsx
  frontend/src/components/common/Calendar/Calendar.styled.ts
  frontend/src/components/common/Calendar/Calendar.tsx
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.styled.ts
  frontend/src/components/common/GoogleSearchPopup/GoogleSearchPopup.tsx
  frontend/src/components/common/Modal/EditRegisterModalBottomSheet/EditRegisterModalBottomSheet.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/TextField/TextField.styled.ts
  frontend/src/components/common/TextField/TextField.tsx
  frontend/src/components/pages/travelPlanRegister/PlaceTodoListItem/PlaceTodoListItem.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.styled.ts
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
Labels: FE

#558 [Fix] - lazy loading 제거
  frontend/src/router.tsx
Labels: FE

#560 [Fix] - 토큰 재발급이 제대로 동작하지 않는 오류 개선
  frontend/src/apis/interceptor.ts
  frontend/src/constants/errorMessage.ts
Labels: FE

#565 [Feature] - 검색 결과 페이지 내 필터링 옵션 적용
  frontend/src/components/pages/search/TravelogueList/TravelogueList.styled.ts
  frontend/src/components/pages/search/TravelogueList/TravelogueList.tsx
  frontend/src/constants/queryKey.ts
  frontend/src/constants/storage.ts
  frontend/src/queries/useInfiniteSearchTravelogues.ts
  frontend/src/queries/useInfiniteTravelogues.ts
Labels: FE

#571 [Refactor] - 톰캣 설정 값 조정을 통한 애플리케이션 서버 성능 튜닝
  backend/src/main/resources/application.yml
Labels: BE

#575 [Fix] - 사용하지 않는 정렬 쿼리 삭제
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueQueryRepositoryImpl.java
Labels: BE

#580 [Fix] - 6차 데모데이 1차 QA(지니)
  frontend/src/components/common/Textarea/Textarea.styled.ts
  frontend/src/components/pages/my/MyTravelPlans/MyTravelPlans.tsx
  frontend/src/components/pages/search/SearchPage.tsx
  frontend/src/constants/storage.ts
Labels: FE

#578 [Fix] - 6차 데모데이 1차 QA(시모)
  frontend/src/components/common/Checkbox/Checkbox.styled.ts
  frontend/src/components/common/Chip/Chip.styled.ts
  frontend/src/components/pages/main/MainPage.tsx
  frontend/src/components/pages/my/MyLikes/MyLikes.tsx
  frontend/src/components/pages/search/TravelogueList/TravelogueList.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
Labels: FE, REFACTOR ♻️

#581 [Fix] - 6차 데모데이 1차 QA(리버)
  frontend/src/components/common/Icon/Icon.styled.ts
  frontend/src/components/common/TopButton/TopButton.styled.ts
  frontend/src/components/common/TopButton/TopButton.tsx
  frontend/src/components/pages/landing/FourthPage/FourthPage.styled.ts
  frontend/src/components/pages/landing/LandingPage.tsx
Labels: FE, REFACTOR ♻️

#583 [Fix] - 랜딩 페이지 페이지 잘리는 문제 및 todo 세로 배열이 맞지 않는 문제
  frontend/src/components/pages/landing/FirstPage/FirstPage.styled.ts
  frontend/src/components/pages/travelPlanDetail/TravelPlanTodoItem/TravelPlanTodoItem.styled.ts
Labels: FE, REFACTOR ♻️

#586 [Feature] - 여행기 나라 관련 리팩토링
  backend/src/main/java/kr/touroot/tag/controller/TagController.java
  backend/src/main/java/kr/touroot/tag/dto/TagCreateRequest.java
  backend/src/main/java/kr/touroot/tag/repository/TagRepository.java
  backend/src/main/java/kr/touroot/tag/service/TagService.java
  backend/src/main/java/kr/touroot/travelogue/domain/TravelogueCountry.java
  backend/src/main/java/kr/touroot/travelogue/domain/TraveloguePlace.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/CountryCode.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/SearchCondition.java
  backend/src/main/java/kr/touroot/travelogue/domain/search/SearchType.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueCountryService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueService.java
  backend/src/main/java/kr/touroot/travelplan/domain/TravelPlanPlace.java
  backend/src/test/java/kr/touroot/tag/TagControllerTest.java
  backend/src/test/java/kr/touroot/tag/fixture/TagFixture.java
  backend/src/test/java/kr/touroot/tag/helper/TagTestHelper.java
  backend/src/test/java/kr/touroot/tag/service/TagServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueCountryTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePlaceTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/search/CountryCodeTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueRequestFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueCountryServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java
Labels: BE

#593 [Fix] - 6차 데모데이 2차 QA(지니)
  frontend/package.json
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueMultiImageUpload/hooks/useMultiImageUpload.ts
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/hooks/usePrompt.ts
  frontend/src/utils/resizeAndConvertImage.ts
  frontend/yarn.lock
Labels: FE

#592 [Fix] - 6차 데모데이 전 2차 QA(시모)
  frontend/src/components/pages/main/MainPage.styled.ts
Labels: FE, REFACTOR ♻️

#597 [Fix] - 뒤로가기 막기 제거
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
Labels: FE

#598 [Feature] - touroot v1.3.3
  frontend/cypress.env.json
  frontend/src/components/pages/travelPlanEdit/TravelPlanEditPage.tsx
  frontend/src/components/pages/travelPlanRegister/TravelPlanRegisterPage.tsx
  frontend/src/components/pages/travelogueEdit/TravelogueEditPage.tsx
  frontend/src/components/pages/travelogueRegister/TravelogueRegisterPage.tsx
  frontend/src/mocks/handlers/index.ts
Labels: FE
