Repository woowacourse-teams/2024-touroot, pull requests merged in 2024-12, with the labels that each got.

#615 [Feature] - graceful shutdown 설정 추가
  backend/src/main/resources/application.yml
Labels: BE

#614 [Feature] - BE 테스트 개선 1단계 Test Fixture 운용 방식 통일 (Enum Fixture)
  backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java
  backend/src/test/java/kr/touroot/authentication/fixture/OauthUserFixture.java
  backend/src/test/java/kr/touroot/authentication/fixture/OauthUserInformationFixture.java
  backend/src/test/java/kr/touroot/authentication/helper/LoginTestHelper.java
  backend/src/test/java/kr/touroot/authentication/service/LoginServiceTest.java
  backend/src/test/java/kr/touroot/member/controller/MemberControllerTest.java
  backend/src/test/java/kr/touroot/member/fixture/MemberFixture.java
  backend/src/test/java/kr/touroot/member/fixture/MemberRequestFixture.java
  backend/src/test/java/kr/touroot/member/helper/MemberTestHelper.java
  backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/CountryCodeTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueCountryTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueDayTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePhotoTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TraveloguePlaceTest.java
  backend/src/test/java/kr/touroot/travelogue/domain/TravelogueTest.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueCountryFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueDayFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TravelogueFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePhotoFixture.java
  backend/src/test/java/kr/touroot/travelogue/fixture/TraveloguePlaceFixture.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueDayRequestBuilder.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueRequestBuilder.java
  backend/src/test/java/kr/touroot/travelogue/helper/TravelogueTestHelper.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlaceTodoTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanDayTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanPlaceTest.java
  backend/src/test/java/kr/touroot/travelplan/domain/TravelPlanTest.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlaceTodoFixture.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanDayFixture.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanFixture.java
  backend/src/test/java/kr/touroot/travelplan/fixture/TravelPlanPlaceFixture.java
  backend/src/test/java/kr/touroot/travelplan/helper/PlanDayRequestBuilder.java
  backend/src/test/java/kr/touroot/travelplan/helper/TravelPlanRequestBuilder.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE, TEST 🧪

#618 [Feature] - 멤버 닉네임 중복을 허용
  backend/src/main/java/kr/touroot/member/service/MemberService.java
  backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java
Labels: BE

#620 [Feature] - 프로덕션 모니터링 구축
  backend/src/main/java/kr/touroot/TourootApplication.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: BE, INFRA ⚙️

#625 [Feature] - BE 테스트 개선 스프링 컨텍스트 캐싱 최적화
  backend/src/main/java/kr/touroot/authentication/service/LoginService.java
  backend/src/test/java/kr/touroot/authentication/controller/LoginControllerTest.java
  backend/src/test/java/kr/touroot/authentication/service/LoginServiceTest.java
  backend/src/test/java/kr/touroot/global/AbstractControllerIntegrationTest.java
  backend/src/test/java/kr/touroot/global/AbstractIntegrationTest.java
  backend/src/test/java/kr/touroot/global/AbstractServiceIntegrationTest.java
  backend/src/test/java/kr/touroot/global/AcceptanceTest.java
  backend/src/test/java/kr/touroot/global/ServiceTest.java
  backend/src/test/java/kr/touroot/image/infrastructure/AwsS3ProviderTest.java
  backend/src/test/java/kr/touroot/member/controller/MemberControllerTest.java
  backend/src/test/java/kr/touroot/member/controller/MyPageControllerTest.java
  backend/src/test/java/kr/touroot/member/service/MemberServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/controller/TravelogueControllerTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueCountryServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueLikeServiceTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/controller/PlaceTodoControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/controller/TravelPlanControllerTest.java
  backend/src/test/java/kr/touroot/travelplan/service/PlaceTodoServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanFacadeServiceTest.java
  backend/src/test/java/kr/touroot/travelplan/service/TravelPlanServiceTest.java
Labels: BE, TEST 🧪, REFACTOR ♻️

#629 [Feature] - Redis cache 도입
  backend/build.gradle
  backend/src/main/java/kr/touroot/global/config/CacheConfig.java
  backend/src/main/java/kr/touroot/tag/cache/CacheConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/kr/touroot/global/AbstractIntegrationTest.java
Labels: BE, INFRA ⚙️
