Repository woowacourse-teams/2024-touroot, pull requests merged in 2024-11, with the labels that each got.

#603 [Feature] - Prometheus, Grafana, Loki 설정 추가
  backend/build.gradle
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: BE, INFRA ⚙️

#607 [Feature] - 로키 어펜더를 dev, prod 에서 동작하도록 변경
  backend/src/main/resources/logback-spring.xml
Labels: BE, INFRA ⚙️

#606 [Feature] - prod db 연결 설정 값 수정
  backend/src/main/java/kr/touroot/global/config/DataSourceConfig.java
  backend/src/main/java/kr/touroot/global/config/DynamicRoutingDataSource.java
  backend/src/main/resources/application.yml
Labels: BE, REFACTOR ♻️

#610 [Feature] - S3 버킷 이름 변경
  backend/src/main/resources/application.yml
Labels: BE, INFRA ⚙️

#613 [Refactor] - logback에 작성된 Loki 설정 수정
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: BE, INFRA ⚙️

#611 [Feature] - 프로덕션 API v1.3.0 배포
  backend/build.gradle
  backend/src/main/java/kr/touroot/global/config/DataSourceConfig.java
  backend/src/main/java/kr/touroot/global/config/DynamicRoutingDataSource.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: BE
