Repository woowacourse-teams/2024-touroot, pull requests merged in 2025-01, with the labels that each got.

#633 [Feature] - 모니터링/로깅 시스템 통합
  .github/workflows/be-cd-dev.yml
  backend/src/main/resources/application.yml
Labels: BE, INFRA ⚙️

#631 [Feature] - 좋아요 순 여행기 목록 조회 페이징 캐싱
  backend/src/main/java/kr/touroot/global/config/CacheConfig.java
  backend/src/main/java/kr/touroot/global/util/PageDeserializer.java
  backend/src/main/java/kr/touroot/global/util/SortDeserializer.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
Labels: BE

#637 [Feature] - 레디스 관련 테스트 코드 작성
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
Labels: BE, INFRA ⚙️, TEST 🧪

#642 [Fix] - dev 환경 Redis host 수정
  backend/src/main/resources/application.yml
Labels: BE, INFRA ⚙️

#644 [Feature] - 인기 여행기 페이징 응답 캐싱 무효화 전략 개선
  backend/src/main/java/kr/touroot/travelogue/domain/Travelogue.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueFacadeService.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
  backend/src/test/java/kr/touroot/global/AbstractRepositoryIntegrationTest.java
  backend/src/test/java/kr/touroot/global/config/TestQueryDslConfig.java
  backend/src/test/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepositoryImplTest.java
  backend/src/test/java/kr/touroot/travelogue/service/TravelogueFacadeServiceTest.java
Labels: BE, REFACTOR ♻️

#647 [Feature] - default_batch_fetch_size 적용
  backend/src/main/resources/application.yml
  backend/src/test/resources/application-test.yml
Labels: BE, REFACTOR ♻️

#649 [Feature] - TravelogueLike 조회를 fetch join으로 개선
  backend/src/main/java/kr/touroot/travelogue/repository/TravelogueLikeRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepository.java
  backend/src/main/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepositoryImpl.java
  backend/src/main/java/kr/touroot/travelogue/service/TravelogueLikeService.java
  backend/src/test/java/kr/touroot/travelogue/repository/query/TravelogueLikeQueryRepositoryImplTest.java
Labels: BE, REFACTOR ♻️
